### ISSUE TITLE
Graph show negative values due to interpolation: how to disable interpolation 

### ISSUE THREAD

**Issue by abdoulosseni** [centreon/centreon-broker#102]
Hello,

Interpolation in centreon makes some graphes showing incorrect values (negative values).
- Centreon : version 2.8
- RRDtool : version 1.4.7

How disable this feature (interpolation)?

**Please see in attachment**.

![graph_issue](https://cloud.githubusercontent.com/assets/27200238/26153411/7b124e54-3b0b-11e7-86d7-72809c937b3b.png)

Regards
Abdoul OSSENI

**Comment by jben94** [comment]
Hi @abdoulosseni ,

The problem is solved in version 2.8.9 : 

https://github.com/centreon/centreon/issues/5143
https://github.com/golgoth31/centreon/commit/04b69d6afe74535397267d6c5a4b6929e13103aa
