### ISSUE TITLE
No more graph after "yum update"

### ISSUE THREAD

**Issue by cmoi42** [centreon/centreon-broker#107]
Hi,

My centreon stop graphing after a "yum update" command (I have updated the whole system and application). 

I can see the following error from /var/log/centreon-broker/central-rrd-master.log : 

[1497278136] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1497278136] error:   std::bad_alloc
Centreon Broker 3.0.7 log file closed

Centreon was installed from a centreon ISO 3.4.1. Hopefully this is a development server configured in a simple architecture.

Below the main compomnents' versions : 

centreon-common-2.8.9-19.el6.noarch
centreon-engine-1.7.2-3.el6.x86_64
centreon-broker-3.0.7-1.el6.x86_64
centreon-web-2.8.9-19.el6.noarch

Thank you for your help,

Regards.

**Comment by ganoze** [comment]
This should have been fixed in the 3.0.8 release. However you might need to delete your retention files to get it to work properly.

If the problem is not gone with Centreon Broker 3.0.8, please generate and send debug log file.

**Comment by cmoi42** [comment]
Thank you for your answer.

It's now graphing correctly after updating and cleaning old retention files.

Regards.
