### ISSUE TITLE
Downtimes with same creation date

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon-broker#108]
Centreon-Broker 3.0.7

Hello,

If I create multiples downtimes for the same service and differents period but with the same creation date, it doesn't work.

For example, I use this command to create two downtimes:
`echo -e 'EXTERNALCMD:2:[1497338546] SCHEDULE_SVC_DOWNTIME;Windows-2012-NRPE;Cpu;1497405600;1497405900;1;0;3600;admin;EEC::Maintenance \nEXTERNALCMD:2:[1497338546] SCHEDULE_SVC_DOWNTIME;Windows-2012-NRPE;Cpu;1497492000;1497492300;1;0;3600;admin;EEC::Maintenance' >> /var/lib/centreon/centcore.cmd`

We see that the timestamp for external command is the same [1497338546].
Only the first downtime will be created.

If I increment the timestamp for the second downtime, it works:
`echo -e 'EXTERNALCMD:2:[1497338546] SCHEDULE_SVC_DOWNTIME;Windows-2012-NRPE;Cpu;1497405600;1497405900;1;0;3600;admin;EEC::Maintenance \nEXTERNALCMD:2:[1497338547] SCHEDULE_SVC_DOWNTIME;Windows-2012-NRPE;Cpu;1497492000;1497492300;1;0;3600;admin;EEC::Maintenance' >> /var/lib/centreon/centcore.cmd`

Regards

**Comment by bouda1** [comment]
I can confirm the bug.

For each downtime, two steps are attempted:
* We try to update the downtime in the database. If it does not already exist, the update fails.
* If the update fails, we insert the row corresponding to the downtime.

The first downtime is well inserted. Whereas the second one is just _updated_ as if they were the same downtime.

**Comment by bouda1** [comment]
Should be fixed soon.

**Comment by thiuyendang** [comment]
Issue reproduced.

**Comment by thiuyendang** [comment]
OK 3.0.10 centreon-broker.
