### ISSUE TITLE
Blocking after an SQL error

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#111]
Hi, 
We encountered an SQL error:

> [1499426475] error:   SQL: could not execute prepared statement: Cannot add or update a child row: a foreign key constraint fails (`centreon_storage`.`services`, CONSTRAINT `services_ibfk_1` FOREIGN KEY (`host_id`) REFERENCES `hosts` (`host_id`) ON DELETE CASCADE) QMYSQL3: Unable to execute statement

This error to block all send to the database, to go into retention files.
To unblock the situation we had to remove the foreign key. 
And everything went off normally.

Would it be possible to make a non-blocking system?

When emptying retention files, we see that the "Last Update" of the pollers is not coherent, see below (Put in chronological order):

![poller1](https://user-images.githubusercontent.com/16583698/27956758-7d159fe8-631b-11e7-9a86-a94de835b3ee.PNG)

![poller2](https://user-images.githubusercontent.com/16583698/27956762-7ffe8be8-631b-11e7-9f80-fab00b465c50.PNG)

![poller3](https://user-images.githubusercontent.com/16583698/27956764-8232622c-631b-11e7-9019-d44818ea9591.PNG)

![poller4](https://user-images.githubusercontent.com/16583698/27956768-879c182a-631b-11e7-9e76-c1c26609d74c.PNG)

![poller5](https://user-images.githubusercontent.com/16583698/27956776-8a73032e-631b-11e7-8a84-901bca892bca.PNG)

![poller6](https://user-images.githubusercontent.com/16583698/27956778-8d343bf0-631b-11e7-974b-d8d6c67e87c1.PNG)

Is normal ?

**Comment by jben94** [comment]
This is our problem.

The actions that caused:

1. Duplication of a host
2. Reload of the poller
3. Removing the same host
4. Reload of the poller

Some services attached to this host remained in memory on the polling.
To remove these ghost services, we did:

1. Stopping the centengine
2. Deleting ".memory." and "retention" related.
3. Restarting centengine

**Comment by jben94** [comment]
centreon web : 2.8.5
centreon engine : 1.7.2
centreon broker : 3.0.7

**Comment by zskarman** [comment]
We got the same
![image](https://user-images.githubusercontent.com/24320218/31716282-69cce328-b407-11e7-920c-b05089630ef2.png)

![image](https://user-images.githubusercontent.com/24320218/31716290-743c231e-b407-11e7-93ce-bc3017b83c6d.png)


and same issue just another tables

https://github.com/centreon/centreon-broker/issues/126

**Comment by bouda1** [comment]
@jben94 , did you install the centreon rpm or is it a home made installation ?
This is important, I have the feeling you missed some migration scripts...
Could you also send a bigger part of the log where you see this error, please ?

Thank you.

**Comment by jben94** [comment]
Hi @bouda1,

This issue is old.
Yes I did an installation via the sources, not RPM. But I believe that @zskarman installed its supervision by RPM.

Since the last versions of the Centreon-broker, these errors are no blocking. So less serious for us!
But sometimes we still have these errors, here are the logs of yesterday:

> [1508311901] error:   SQL: could not store host group membership (poller: 10, host: 145, group: 235): could not execute prepared statement: Duplicate entry '145-235' for key 'host_id' QMYSQL3: Unable to execute statement
> [1508311902] error:   SQL: could not store host group membership (poller: 10, host: 145, group: 71): could not execute prepared statement: Duplicate entry '145-71' for key 'host_id' QMYSQL3: Unable to execute statement
> [1508311903] error:   SQL: could not store host group membership (poller: 10, host: 145, group: 84): could not execute prepared statement: Duplicate entry '145-84' for key 'host_id' QMYSQL3: Unable to execute statement
> [1508311903] error:   SQL: could not store host group membership (poller: 10, host: 145, group: 122): could not execute prepared statement: Duplicate entry '145-122' for key 'host_id' QMYSQL3: Unable to execute statement
> [1508311903] error:   SQL: could not store host group membership (poller: 10, host: 145, group: 133): could not execute prepared statement: Duplicate entry '145-133' for key 'host_id' QMYSQL3: Unable to execute statement

**Comment by zskarman** [comment]
Hi,

I used the repo RPM and not less serious, because at our environment is stopped 5-6 times / day. and at that time the broker has stopped. now we have an cron to check the log file and when its happen reload the cbd.

but this is not right because its generate lots of false events into the DB.

Regards, Zsolt

**Comment by bouda1** [comment]
hi #zskarman
thank you for your precisions.
The issues you encounter look like this issue but I think they have no common way.
I still work on it.
Regards.

**Comment by zskarman** [comment]
Hi,

Mostly happen if i move one host between pollers. The CDB looks see as an new checks, instead of moved host's checks.

For temporary could I build an custom cbd to ignore those, because still the broker has stops each of the times.
Also this error happens with the new checks as well.

Regards, Zsolt

**Comment by omercier** [comment]
I believe this issue has been fixed long ago.
