### ISSUE TITLE
[3.0.10] Connection lost when One peer retention is activate

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon-broker#134]
Configure a Central and a poller using One peer retention i.e. the central try to recover Centreon Broker datas on the poller.

Disconnect the network cable of the poller.
Wait about 10 minutes.
Reconnect the network cable.

Central is unable to recover the datas : the only solution is to restart Centengine

**Comment by Sims24** [comment]
Hi, 

You should tweak the tcp_retries kernel param to make it reconnect quicker.

**Comment by Sims24** [comment]
Hi @lolokai, 

We had similar issues. 

Please optimize TCP kernel parameters on poller and central as below : 

```
echo 3 > /proc/sys/net/ipv4/tcp_retries2
echo 200 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 2 > /proc/sys/net/ipv4/tcp_keepalive_probes
echo 2 > /proc/sys/net/ipv4/tcp_keepalive_intvl
```

You should not have this issue anymore. 

Thanks

**Comment by lolokai** [comment]
Hello Simon,

Should I activate it on each side i.e. Central server and Poller server ?

**Comment by Sims24** [comment]
Hello Loïc, 

Yes ! 

Simon

**Comment by benrobert** [comment]
Hi,
I experience same issues and the TCP kernel parameters optimizations does not seems to work.

When the connection between the central and a poller in one peer retention mode is lost, it take at least 4 or 5min for the tcp connection to be established again. This is for small environment with few pollers. On bigger environment this could take more than 15min, which cause a lot of retention and other problems. 

Restarting engine on the poller solve the problem but this is annoying with lot of pollers and in the followed use case :
When implementing stream connector we need to restart broker quite often, which cut the connexion.

As the connexion is cut by broker itself, maybe we could think of a way to close gently the remote socket, and not wait for it's timeout.

**Comment by bouda1** [comment]
This bug is quite old and the tcp connector in broker is no more the same. I close this issue. But feel free to open a new issue if you have the issue again.
