### ISSUE TITLE
error: ‘isnan’ was not declared in this scope

### ISSUE THREAD

**Issue by maxdevaine** [centreon/centreon-broker#139]
Hello,
I have a problem with compiling on Debian Stretch 64bit.

`
[ 75%] Building CXX object storage/CMakeFiles/20-storage.dir/mnt/datastore/temp/centreon-broker/storage/src/metric.cc.o
[ 75%] Building CXX object storage/CMakeFiles/20-storage.dir/mnt/datastore/temp/centreon-broker/storage/src/metric_mapping.cc.o
[ 76%] Building CXX object storage/CMakeFiles/20-storage.dir/mnt/datastore/temp/centreon-broker/storage/src/parser.cc.o
/mnt/datastore/temp/centreon-broker/storage/src/parser.cc: In function ‘void extract_range(double*, double*, bool*, const char**)’:
/mnt/datastore/temp/centreon-broker/storage/src/parser.cc:99:25: error: ‘isnan’ was not declared in this scope
     if (!isnan(low_value))
                         ^
/mnt/datastore/temp/centreon-broker/storage/src/parser.cc:99:25: note: suggested alternative:
In file included from /mnt/datastore/temp/centreon-broker/storage/src/parser.cc:22:0:
/usr/include/c++/6/cmath:662:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^~~~~
/mnt/datastore/temp/centreon-broker/storage/src/parser.cc:106:25: error: ‘isnan’ was not declared in this scope
     if (isnan(high_value)
                         ^
/mnt/datastore/temp/centreon-broker/storage/src/parser.cc:106:25: note: suggested alternative:
In file included from /mnt/datastore/temp/centreon-broker/storage/src/parser.cc:22:0:
/usr/include/c++/6/cmath:662:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^~~~~
/mnt/datastore/temp/centreon-broker/storage/src/parser.cc: In member function ‘void com::centreon::broker::storage::parser::parse_perfdata(const QString&, QList<com::centreon::broker::storage::perfdata>&)’:
/mnt/datastore/temp/centreon-broker/storage/src/parser.cc:240:24: error: ‘isnan’ was not declared in this scope
     if (isnan(p.value()))
                        ^
/mnt/datastore/temp/centreon-broker/storage/src/parser.cc:240:24: note: suggested alternative:
In file included from /mnt/datastore/temp/centreon-broker/storage/src/parser.cc:22:0:
/usr/include/c++/6/cmath:662:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^~~~~
storage/CMakeFiles/20-storage.dir/build.make:230: recipe for target 'storage/CMakeFiles/20-storage.dir/mnt/datastore/temp/centreon-broker/storage/src/parser.cc.o' failed
make[2]: *** [storage/CMakeFiles/20-storage.dir/mnt/datastore/temp/centreon-broker/storage/src/parser.cc.o] Error 1
CMakeFiles/Makefile2:717: recipe for target 'storage/CMakeFiles/20-storage.dir/all' failed
make[1]: *** [storage/CMakeFiles/20-storage.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
` 

Is this a bug or is a problem somewhere else?

Thank you
Max Devaine

**Comment by bouda1** [comment]
Hi,

Le C++ compiler of Debian compiles in c++11 by default now.

So, to compile centreon-broker open the file build/CMakeLists.txt with your favorite text editor and
add the following line just after `project("Centreon Broker" C CXX)`  :
                                           
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++98 -fpermissive)`

Then, in the terminal, you should be able to compile:
`cd build`
`make clean`
`make`

`make clean` is useful to clear your previous compilation.

**Comment by maxdevaine** [comment]
Hello,
thanks, this works and now is all ok.

Max
