### ISSUE TITLE
[InfluxDB] - Timestamp Error 

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#142]
Hi,

I'm having a problem with the "InfluxDB" output
It can not insert into database because it finds a value of timestamp equal to zero.

Example : centreon.status.***.TRAP_0002,index_id=125414920 value=0 0

Is it possible to reject this value and not loop on this error?

Regards

**Comment by jben94** [comment]
Hi,
I also notice that the statuses of Traps are sent and go up in error because the Timestamp leaves the retention configured on the database.

**Comment by jben94** [comment]
While waiting for an official solution, I modified the influxdb12.cc file like this:

```
  if ((split[0] == "HTTP/1.0")
      && (split[1] == "204")
      && (split[2] == "No")
      && (split[3] == "Content"))
    return (true);
  else if (strstr(ans.c_str(), "points beyond retention policy dropped")) {
    logging::error(logging::medium)
      << "influxdb: got an error from '"
      << _socket->peerAddress().toString()
      << "' and port '" << _socket->peerPort() << "': '"
      << ans << "'";
  } else
    throw (exceptions::msg()
      << "influxdb: got an error from '"
      << _socket->peerAddress().toString()
      << "' and port '" << _socket->peerPort() << "': '"
      << ans << "'");
```

**Comment by adr1enb** [comment]
Hello @jben94 
I have the same issue, influxdb with 31d retention enabled, when we add a new host on centreon, the first value sent has the timestamp 0.
I would like to apply your modification, can we give more information on what to do ?

**Comment by jben94** [comment]
Hello @adr1enb 
- Download the last version "centreon-broker": https://download.centreon.com/
- Change the file "influxdb12.cc", as above.
- Compile centreon-broker, as indicated in the documentation: https://documentation.centreon.com/docs/centreon-broker/en/latest/installation/index.html#using-sources

Good luck !

**Comment by adr1enb** [comment]
@jben94 Thanks but unfortunately, we have installed all our new infrastructure with packages, we would not want to compile Centreon-broker..
We really hope it can be fix soon on centreon-broker.

**Comment by bouda1** [comment]
Hi,

We made a fix a little time ago on the influxdb connector. Do you know if you always have the issue on the last 20.04, 20.10 versions?
Thanks.

**Comment by jben94** [comment]
Hi,

It will be difficult for me to test because I am not with the customer who had this problem. 
And since, I use a streamconnector.

I think this issue can be closed.
