### ISSUE TITLE
[BAM] A boolean that has been modified isn't correctly updated

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon-broker#145]
Centreon 2.8.15
Centreon Broker 3.0.11
Centreon Engine 1.8.1

Sorry, I couldn't find a shorter path to reproduce the problem :-)

1. Create a BA-1 and a boolean-1 linked to a service-x
2. Push the configuration 
3. Force the boolean-1 KPI to a OK state (service-x = OK)
4. Create a second boolean-2 linked to another service-y and attach it to the BA-1 _(no matter on what BA this KPI is anyway)_
5. Push the configuration
6. Force the boolean-2 KPI to a OK state (service-y = OK)
7. Modify the **boolean-1** so that it's now linked to a **service-y**
8. Push the configuration
9. Make the **service-y** CRITICAL 

**Describe the results you received:**
Only **boolean-2** becomes CRITICAL. The boolean-1 stays OK. No matter how many times you make the service-y changes from OK to CRITICAL, the boolean-1 will always stay in OK state.

**Describe the results you expected:**
A modified boolean should always be updated, in that case, the **boolean-2** should be CRITICAL. 

**Use case** : You describe an application in Centreon BAM and have boolean KPIs based on some host. The host hosting the application are changed so you want to update some KPIs with their new names etc.. In that case, regarding to the way the user do that, they encounter the problem described below.

**Comment by bouda1** [comment]
If we look at the logs during the described manipulation, we get this:

`[1512749240] config:  applier: 14 modules loaded`
`[1512749240] config:  endpoint applier: loading configuration`
`[1512749240] config:  BAM: creating BA 7 ('BA-DBR')`
`[1512749240] config:  BAM: creating new boolean expression 13`
`[1512749240] config:  BAM: creating new KPI 15 of boolean expression 13 impacting BA 7`
`[1512749359] config:  main: configuration update requested`
`[1512749359] config:  log applier: applying 1 logging objects`
`[1512749359] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'`
`[1512749359] config:  applier: 14 modules loaded`
`[1512749359] config:  endpoint applier: loading configuration`
`[1512749359] config:  BAM: modifying BA 7`
`[1512749359] config:  BAM: creating new boolean expression 14`
`[1512749359] config:  BAM: removing KPI 15`
`[1512749359] config:  BAM: creating new KPI 15 of boolean expression 13 impacting BA 7`
`[1512749359] config:  BAM: creating new KPI 16 of boolean expression 14 impacting BA 7`
`[1512749485] config:  main: configuration update requested`
`[1512749485] config:  log applier: applying 1 logging objects`
`[1512749485] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'`
`[1512749485] config:  applier: 14 modules loaded`
`[1512749485] config:  endpoint applier: loading configuration`
`[1512749485] config:  BAM: removing boolean expression 13`
`[1512749485] config:  BAM: creating new boolean expression 13`
`[1512749485] config:  BAM: removing KPI 16`
`[1512749485] config:  BAM: creating new KPI 16 of boolean expression 14 impacting BA 7`

And we can observe that:
* expression 13 is linked to BA 7 by KPI 15.
* expression 14 is linked to BA 7 by KPI 16.

But at the end, during the last manipulation, expression 13 is removed/created whereas KPI 16 is removed/created. So KPI 15 and expression 13 are linked to nothing.
And we get the bad result.

I work on the subject to fix this.

**Comment by adr-mo** [comment]
Looks good to me.
