### ISSUE TITLE
Centreon Broker ne démarre pas après mise

### ISSUE THREAD

**Issue by hvad** [centreon/centreon-broker#146]
Bonjour,

Après la mise à jour de centreon 2.6 vers 2.8 sur RHEL 6 x86_64, centreon broker ne démarre plus et le fichier de configuration de "watchdog" est vide. 

Ou est la documentation sur la partie watchdog de centreon ? 

Cordialement

**Comment by SylvestreG** [comment]
this old version are not still supported. Please re-open if you reproduce on current versions.
