### ISSUE TITLE
Graph rebuild is too slow

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon-broker#16]
Comment of Damien Duponchelle:

I'm working with 20 0000 services, I had a issue this night and I have hole in all graphics.
I'm able to solve the problem by rebuilding graphs, the rebuild process is very slow and heavy.

Rebuild 100 graphs takes some hours, rebuilding 20K services is impossible.

A solution must be found in order to get a very fast rebuild.

**Comment by ganoze** [comment]
Comment of Kevin Duret:

I think Centreon-Broker should look if data_bin is partitioned.
If yes, rebuild graph day by day (or month by month, depends of partitioning option).

**Comment by florian-asche** [comment]
+1

**Comment by bouda1** [comment]
From cbd 22.04.x (the next release), rebuild will be faster thanks to several improvements:
* new bbdo events with protobuf embedded
* gRPC commands to ask for rebuild/deletion.
* Queries take care of data_bin partitions.
