### ISSUE TITLE
Wrong bam configuration cause a segfault on broker

### ISSUE THREAD

**Issue by pkriko** [centreon/centreon-broker#164]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.18

**Centreon Engine version**:  1.8.1

**Centreon Broker version**: 3.0.13

**OS**: Centos 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a bolean rule with a kpi that doesn't not exist anymore
2. Reload the configuration/Restart cbd
3.

**Describe the results you received:**
CBD doesn't start.

**Describe the results you expected:**
CBD start with BAM error but don't have a segfault

**Additional information you think important (e.g. issue happens only occasionally):**
The error message : cbd[193777]: segfault at 0 ip 0000003c1e86f2cc sp 00007f5bfe1f4ea0 error 4 in libQtCore.so.4.7.4[3c1e800000+279000]

**Comment by adr-mo** [comment]
Hey,

It also happens with a disable META and BA as KPI.

It could be interresing to check this cases out !

thanks
