### ISSUE TITLE
[InfluxDB] SSL support ?

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-broker#182]
Hi,

Does InfluxDB supports SSL ?

I have such endpoint :
`https://token:mypassword@host/write`

So I use it like this (not sure everything is correct though) :

![end](https://user-images.githubusercontent.com/40244829/44046661-6cefca78-9f2c-11e8-97c7-f74c087c1a47.png)

Seems to connect :

![conn](https://user-images.githubusercontent.com/40244829/44046493-ee083330-9f2b-11e8-8f6f-375cb7439db3.png)

But then in `central-broker-master.log` I get :
`[1534178931] error:   influxdb: couldn't receive InfluxDB answer with address '' and port '0': The remote host closed the connection`

I then wonder whether or not SSL is supported.

Thank you very much 👍

**Comment by Sims24** [comment]
Hi, 

You should prefer using stream connector to send data into influxdb. 

Take a look at https://github.com/centreon/centreon-stream-connector-scripts

**Comment by CPbN** [comment]
Thank you for your answer @Sims24.
Does it mean Stream Connector is now the preferred method over other _Broker_ outputs,
such as Graphite & InfluxDB ?

As for now, I configured the _Engine_ like this :

![ent](https://user-images.githubusercontent.com/40244829/44074789-62cf22aa-9f9a-11e8-96e3-fde6301108c5.png)

`/tmp/centreon-perfdata` is a pipe red by another program which buffers and processes the data.

Is it a Centreon configuration you would recommend / you'll keep supporting ?

Thank you again !

**Comment by Sims24** [comment]
You're welcome.

Actually processing perfdata is not recommended and will probably generate some performance issues on a larger scope. Please do not use it.

And yes stream connectors are the best options and the one that will elvolve in the futur instead of the legacy graphite or influxdb outputs.

**Comment by CPbN** [comment]
I'll then close this issue linking to the Stream Connector Scripts [repository](https://github.com/centreon/centreon-stream-connector-scripts).
Thx :+1:
