### ISSUE TITLE
[Enhancement] command service cbd status

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-broker#184]
Hi,

It would be nice to have a return message when we use the command "service cbd status".
if cbd is stopped, this command return nothing.

We are in progress automaticating of system upgrading without centreon packages.
We include a reboot of the server after upgrade. And for that we verifying somes processes are running or not.
It's for that we needs to have this message

I add theses lines in /etc/init.d/cbd

# Status
status_watchdog() {
  if [ -f "${pidfile}" ] ; then
    status -p ${pidfile} ${cbwd}
  **_else
    echo "Centreon Broker watchdog is not running."_**
  fi
}

Thanks,

**Comment by SylvestreG** [comment]
we now use systemctl, looks fix with it
