### ISSUE TITLE
Error Insert to database - data_bin

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#190]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10

**Centreon Engine version**: 18.10

**Centreon Broker version**: 18.10

**OS**: 7.5

**Database**: MySQL 5.6

**Describe the results you received in log:**

[1543339384] error:   storage: could not insert data in log_data_bin: could not execute query: Data truncated for column 'status' at row 1 QMYSQL: Unable to execute query (INSERT INTO data_bin  (id_metric   , ctime, status, value)  VALUES (1329651, 1543312215, 0, '3.6488000000e-02'), (1500316, 1543312219, 0, 5.1031000000e-02), (1500317, 1543312219, 0, 4.8800000000e+02), (1500315, 1543312220, 0, 3.1488000000e-02), (1407087, 1543312228, 0, 6.8551200000e+08)...)

Being defined ENUM ('0', '1', '2', '3', '4') (equivalent to a string), in database.
For the request to be correct, add (') for the' status' field.

Why the first value is a string and the others are not?

Current code:

```
    // Insert first entry.
    std::ostringstream query;
    {
      metric_value& mv(_perfdata_queue.front());
      query.precision(10);
      query << std::scientific
            << "INSERT INTO " << (db_v2 ? "data_bin" : "log_data_bin")
            << "  (" << (db_v2 ? "id_metric" : "metric_id")
            << "   , ctime, status, value)"
               "  VALUES (" << mv.metric_id << ", " << mv.c_time << ", "
            << mv.status << ", '";
      if (isinf(mv.value))
        query << ((mv.value < 0.0) ? -FLT_MAX : FLT_MAX);
      else if (isnan(mv.value))
        query << "NULL";
      else
        query << mv.value;
      query << "')";
      _perfdata_queue.pop_front();
    }

    // Insert perfdata in data_bin.
    while (!_perfdata_queue.empty()) {
      metric_value& mv(_perfdata_queue.front());
      query << ", (" << mv.metric_id << ", " << mv.c_time << ", "
            << mv.status << ", ";
      if (isinf(mv.value))
        query << ((mv.value < 0.0) ? -FLT_MAX : FLT_MAX);
      else if (isnan(mv.value))
        query << "NULL";
      else
        query << mv.value;
      query << ")";
      _perfdata_queue.pop_front();
}
```

Correction:

```
    // Insert first entry.
    std::ostringstream query;
    {
      metric_value& mv(_perfdata_queue.front());
      query.precision(10);
      query << std::scientific
            << "INSERT INTO " << (db_v2 ? "data_bin" : "log_data_bin")
            << "  (" << (db_v2 ? "id_metric" : "metric_id")
            << "   , ctime, status, value)"
               "  VALUES (" << mv.metric_id << ", " << mv.c_time << ", '"
            << mv.status << "', ";
      if (isinf(mv.value))
        query << ((mv.value < 0.0) ? -FLT_MAX : FLT_MAX);
      else if (isnan(mv.value))
        query << "NULL";
      else
        query << mv.value;
      query << ")";
      _perfdata_queue.pop_front();
    }

    // Insert perfdata in data_bin.
    while (!_perfdata_queue.empty()) {
      metric_value& mv(_perfdata_queue.front());
      query << ", (" << mv.metric_id << ", " << mv.c_time << ", '"
            << mv.status << "', ";
      if (isinf(mv.value))
        query << ((mv.value < 0.0) ? -FLT_MAX : FLT_MAX);
      else if (isnan(mv.value))
        query << "NULL";
      else
        query << mv.value;
      query << ")";
      _perfdata_queue.pop_front();
    }
```

Regards

**Comment by bouda1** [comment]
Yes, you are right. But this is because your database is in strict mode.
Otherwise the query should be accepted. And even if you make the change you propose, many queries in the centreon php need a permissive mode. And therefore, the web interface will probably also fail.

But you are right and the next version of broker will fix it.
Thank you.

**Comment by bouda1** [comment]
It will be fixed on next release.
