### ISSUE TITLE
Problem with metrics using to much space

### ISSUE THREAD

**Issue by nikitito** [centreon/centreon-broker#219]
Hi,
I just notice after an import yesterday ( 33 hosts ), that my metrics are using too much space in no time. I don't know why, does someone has an idea please ?
Thank you in advance.
---root@localhost:/var/lib/centreon/metrics# date && ls -l | wc -l
jeu. juin 13 12:01:33 CEST 2019
72824
---root@localhost:/var/lib/centreon/metrics# date && df -h
jeu. juin 13 12:02:56 CEST 2019
Sys. de fichiers                     Taille Utilisé Dispo Uti% Monté sur
/dev/mapper/centos-root    47G     45G  2,9G  95% /
---root@localhost:/var/lib/centreon/metrics# date && ls -l | wc -l
jeu. juin 13 12:02:59 CEST 2019
72876
---root@localhost:/var/lib/centreon/metrics# date && df -h
jeu. juin 13 12:09:17 CEST 2019
Sys. de fichiers                     Taille Utilisé Dispo Uti% Monté sur
/dev/mapper/centos-root    47G     45G  2,8G  95% /
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
           Centreon 19.04.0
**Centreon Engine version**: 
           Centreon Engine 19.04.0
**Centreon Broker version**: 
            Centreon Broker 19.04.0
**OS**: 
            CentOS Linux release 7.6.1810 (Core)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
            VM ESXI 5.1

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by bouda1** [comment]
Hi,

RRD files are built when centreon starts. But there sizes are fixed and won't grow up. So if you don't add any host, those directories sizes won't change in the future.

Regards.

**Comment by nikitito** [comment]
But it is...
Cf : results of commands I posted
