### ISSUE TITLE
CBD sql/rrd/module won't start/restart if special character in configuration files' names.

### ISSUE THREAD

**Issue by thibaults-centreon** [centreon/centreon-broker#222]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
19.04.0
**Centreon Engine version**: 
19.04.0
**Centreon Broker version**: 
19.04.0
**OS**: 
CentOS Linux release 7.6.1810 (Core)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Steps to reproduce the issue:**
1. Modify Central/Remote Server name in poller configuration using a "." character in the name
2. Rename Broker configuration entries (name/config file/log file) using the same character
3. Export configuration and manually restart cbd process

**Describe the results you received:**
Cbd is restarting but only the watchdog process is running. RRD/SQL/Module processes won't load if there's a special character in configuration

**Describe the results you expected:**
The "." character should not be interpreted by systemctl or using special characters should not be allowed to be used in the configuration forms.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by bouda1** [comment]
Hi @thibaults-centreon

Thanks for this report.
@lpinsivy, there are forbidden characters in the broker names but they are not the same between the web interface and broker. We should do something more consistent. :-)

**Comment by bouda1** [comment]
It is fixed on master, next 20.04 and next 20.10
