### ISSUE TITLE
TCP keep-alive don't seems to work . 

### ISSUE THREAD

**Issue by und3ath** [centreon/centreon-broker#228]
Centreon Web Version : 19.04.2

Centreon Engine Version : 19.04.1

Centreon Broker Version : 19.04.0

Centos 7 installed from Centreon ISO . 

Virtual server running into vmware infrastructure . 

Hello , we have all our pollers in one-peer retention mode . 
It appear when a network failure occure that the socket of cbd (5669) on the central keep in 'ESTABLISHED' state  when doing netstat . The socket on the poller return in the listening state successfully . 

We have set        echo 300 > /proc/sys/net/ipv4/tcp_keepalive_time   and starting to capture traffic . It seems that keep-alive packets are not sent .  

On the ssh and mysql socket we see the keep-alive packets as exepted . 

Maybe a QT issue ?

**Comment by bouda1** [comment]
Hi @und3ath

As we are removing QT from centreon-broker, we need to replace the QTcpSockets. We make our best to fix this bug by the way.

**Comment by bouda1** [comment]
This is no more the case with centreon-broker 20.04.9 or centreon-broker 20.10.0.
