### ISSUE TITLE
Memory leak on Centreon-Broker 2.8.2

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-broker#23]
Hi, 

All is in the title, since I upgraded to Centreon-broker 2.8.2, I can see that the memory of my server rises again and again ... 

![broker-memory-leak](https://cloud.githubusercontent.com/assets/12429463/8869788/6f6a4b7a-31e8-11e5-80f8-aaa8d3e60579.png)

Restart the service free the memory.

My feeling is that this leak is in my output from broker-sql to broker-rrd. 

Broker-rrd memory consumption is OK :)

Could you please fix this ?

Thanks

**Comment by ganoze** [comment]
Confirmed and fixed by afouille.
