### ISSUE TITLE
BAM: difference between ba_event and kpi_event

### ISSUE THREAD

**Issue by pkriko** [centreon/centreon-broker#231]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
19.04.3
**Centreon Engine version**: 
19.04.1
**Centreon Broker version**: 
19.04.0
**OS**:
CentOS 7.6 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMs on VMWARE

**Steps to reproduce the issue:**
1. Create a BA and check "Automatically inherit KPI downtimes ?"
2. Set a Downtime on a KPI
3. Simulate a critical on this KPI (So my BA is in downtime)
4. Remove the downtime on my KPI (So my BA is not anymore in downtime)

**Describe the results you received:**
I have no kpi_event_id list for my ba_event_id when my the downtime is removed :
SELECT ba_event_id, ba_id, FROM_UNIXTIME(start_time) as start_time, first_level, FROM_UNIXTIME(end_time) as end_time, status, in_downtime FROM mod_bam_reporting_ba_events;
+-------------+-------+---------------------+-------------+---------------------+--------+-------------+
| ba_event_id | ba_id | start_time          | first_level | end_time            | status | in_downtime |
+-------------+-------+---------------------+-------------+---------------------+--------+-------------+
|           1 |     1 | 2019-08-02 16:12:33 |         100 | 2019-08-02 16:19:26 |      0 |           0 |
|           2 |     1 | 2019-08-02 16:19:26 |          50 | 2019-08-02 16:24:26 |      2 |           1 |
|           3 |     1 | 2019-08-02 16:24:26 |          50 | 2019-08-02 16:34:26 |      2 |           0 |
|           4 |     1 | 2019-08-02 16:34:26 |         100 | NULL                |      0 |           0 |
+-------------+-------+---------------------+-------------+---------------------+--------+-------------+

SELECT kpi.kpi_event_id, kpi_id, FROM_UNIXTIME(start_time) as start_time, FROM_UNIXTIME(end_time) as end_time, status, in_downtime, impact_level, first_output, first_perfdata FROM mod_bam_reporting_kpi_events kpi, mod_bam_reporting_relations_ba_kpi_events r WHERE kpi.kpi_event_id=r.kpi_event_id AND r.ba_event_id=3;
Empty set (0.00 sec)

**Describe the results you expected:**

 SELECT kpi.kpi_event_id, kpi_id, FROM_UNIXTIME(start_time) as start_time, FROM_UNIXTIME(end_time) as end_time, status, in_downtime, impact_level, first_output, first_perfdata FROM mod_bam_reporting_kpi_events kpi, mod_bam_reporting_relations_ba_kpi_events r WHERE kpi.kpi_event_id=r.kpi_event_id AND r.ba_event_id=2 and status != 0;
+--------------+--------+---------------------+---------------------+--------+-------------+--------------+---------------------------------------------------+-------------------+
| kpi_event_id | kpi_id | start_time          | end_time            | status | in_downtime | impact_level | first_output                                      | first_perfdata    |
+--------------+--------+---------------------+---------------------+--------+-------------+--------------+---------------------------------------------------+-------------------+
|            2 |      2 | 2019-08-02 16:19:26 | 2019-08-02 16:24:26 |      2 |           1 |           50 | CRITICAL: Number of current processes running: 0
 | 'nbproc'=0;;1:;0; |
|            5 |      2 | 2019-08-02 16:24:26 | 2019-08-02 16:34:26 |      2 |           0 |           50 | CRITICAL: Number of current processes running: 0
 | 'nbproc'=0;;1:;0; |
+--------------+--------+---------------------+---------------------+--------+-------------+--------------+---------------------------------------------------+-------------------+
2 rows in set (0.00 sec)

The kpi_event_id = 5 normally must be linked to the ba_event_id 3

And so If I generate a report, I will have a exception with no linked KPI under it.

**Additional information you think important (e.g. issue happens only occasionally):**
I have checked with Etienne, if you need more informations, he'll known :)

**Comment by Moujimouja** [comment]
Fixed here > this can be close 

https://github.com/centreon/centreon-broker/pull/374
