### ISSUE TITLE
Centreon Engine crashes from time to time

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon-broker#24]
Hello Centreon Support,

i have multiple instances of centreon, they do not depend or known of each other. 
They are all build an structured in the same way.

1 of 5 Centreon Systems get from time to time a problem. Centreon Engine Crashed internally, i think because of the broker module, that has some problem.

The Centreon Engine stops sending the data with tcp, it switched to failover.

Restarting the engine is not that easy, because it appears to be in a endless loop. 

I did a strace -p on the process and find a lot of this:
poll([{fd=8, events=POLLIN}], 1, 0)     = 0 (Timeout)

[xxx@xxx:NOENV]-(~)$ sadm lsof | grep 1896819775
COMMAND     PID         USER   FD      TYPE DEVICE SIZE/OFF NODE NAME
centengin 22082 USERXY    8r     FIFO                0,8        0t0 1896819775 pipe
centengin 22082 USERXY    9w     FIFO                0,8        0t0 1896819775 pipe

I activated the debug logging, if we can get in contact, i can send u the file.

You can contact me via Google Talk: florian.asche1@gmail.com

**Comment by florian-asche** [comment]
We maybe found the problem: old vmware driver (version 8) we upgrade in some days to version 10.

**Comment by ganoze** [comment]
All right, let met know if this fix your problem. Otherwise I would be glad to fetch a core dump of the process (gcore <pid>) along with its memory map (/proc/<pid>/maps).

**Comment by florian-asche** [comment]
Hi,
after the change to the new Version 10 of vmWare, Engine or Broker never again crashed. 
;)

**Comment by ganoze** [comment]
Thank you for your report. I'm glad to hear that the issue you faced was not of Centreon Broker's fault.

Regarding the note to the documentation it's been added in 2.11 and master branches. It's expected to be online some time soon.

**Comment by ganoze** [comment]
Note was added to online documentation.
