### ISSUE TITLE
Check retention file integrity

### ISSUE THREAD

**Issue by cweiland** [centreon/centreon-broker#26]
Hello,
I have lot of potentially corrupt retention files. Is there a specific application/script to check them and say which of them are corrupted ?

Thanks a lot,
Christophe

**Comment by afouille** [comment]
Hello,
Unfortunately, no. We are trying to implement mechanisms to ensure that, even in the case of serious file corruption, broker replays the file graciously by ignoring corrupted packets. This doesn't help you right now, though.

It should be possible to create a dummy centreon-broker configuration that tries to replay the files and watch the replay status in Broker's stat file for corruption. This could be reasonably automated.

Best regards,

**Comment by ganoze** [comment]
Unit test were implemented to test various cases of retention file corruption. This will ensure that Centreon Broker properly process them.
