### ISSUE TITLE
Wrong information in stats

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon-broker#27]
Hi,
in stats output there is some information, i think they are not correct:

For example: input: event processing speed=0.0 events/s, should be higher than zero.

broker
version=2.9.2
pid=815
now=1441361228
compiled with qt=4.7.4
running with qt=4.7.4

**Comment by ganoze** [comment]
Indeed for acceptor inputs (that is listening sockets), the event processing speed is 0. This won't likely be fixed in the 2.x branch.

Thank you for your report anyway.
