### ISSUE TITLE
qt4 to be removed in next Debian release

### ISSUE THREAD

**Issue by sdelafond** [centreon/centreon-broker#277]
I maintain the centreon libraries in Debian, and as pointed in https://bugs.debian.org/939626, centreon-broker will not be able to be included in the next Debian release since it's using Qt4.

I'm opening this bug mostly so we can have a proper discussion channel, and figure out early if there are plans for upstream to adopt Qt5 in a somewhat near future. That'll help us on the Debian side in planning what needs to happen next.

Cheers !

**Comment by bouda1** [comment]
Hi @sdelafond,

We are working actively on that subject. So the next release of centreon-broker won't need qt4 nor qt5. Qt will be completely removed from it. We hope this change to be finish for the next release of Centreon.
Thank you for your feedback.
Cheers.

**Comment by mmuehlenhoff** [comment]
Is this fixed in 19.10.0?

**Comment by SylvestreG** [comment]
Hi,

Sorry we were too late to make it through 19.10.0, the amount of work to get rid of Qt was bigger than expected. The no-qt branch is becoming stable, for sure it will be in 20.04, but I personally hope to get it in 19.10.x 

Cheers,

**Comment by SylvestreG** [comment]
there is no qt left in master, this will hit 20.04

**Comment by rikmills** [comment]
If centreon-broker is to remain in Ubuntu 20.04, there will need to be a release the non Qt version quite soon. Feature freeze is in just under 3 weeks.

**Comment by SylvestreG** [comment]
Hi Rik, 

Next version of centreon-broker (20.04 same as Ubuntu) will be released on April 2020. This version will be shipped without Qt dependencies. The master is still Qt free (even if it still needs some stabilization). 

Older version of broker like 19.10 will continue to needs Qt4, QT was way too deep into broker to backport these changes in previous releases...

Is it possible to ship a beta centreon-broker 20.04 based on master into ubuntu 20.04 ? and update the package with the released broker 20.04 when the release will be done. If not it's sad but I think we will not make ubuntu 20.04 and hope to be back for Ubuntu 20.10

Thanks for you feedback, and sorry for the bad timing...

Cheers,
