### ISSUE TITLE
Correlation engine is NOT loaded

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-broker#28]
Hi,

What causes these errors:
[1441633153] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1441633153] config:  correlation: invalid correlation configuration, correlation engine is NOT loaded

I see them in central-module-master.log and also in central-master-rrd.log and also in central-broker-master.log

**Comment by ganoze** [comment]
The first line (*config: module applier: loading directory*) is just an informational message that specifies from which directory Centreon Broker modules will be loaded (without modules Centreon Broker would be useless). There's no impect on the second line.

The second line (*config: correlation: invalid correlation configuration*) is generated by the correlation module. It states that no or invalid configuration was provided to the module (there should be a *<correlation>* section in the main configuration file). The correlation module is used to aggregate errors on the IT network graph and provide root issues. However most Centreon setups do not use this feature yet. Therefore the correlation configuration is not generated and the module prints an error. Nothing harmful you see.

**Comment by kadrika** [comment]
Do you recommend to use the correlation module?

**Comment by ganoze** [comment]
To make this module useful you need a quite big network to monitor (30k+ services) and spend a lot of time to declare all dependencies and parenting between hosts and services.

For most users I would not recommend to use this module.

**Comment by kadrika** [comment]
Ok, thanks for the update!
