### ISSUE TITLE
duplicate entries in logs table

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-broker#283]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  All version > 2.8

**Centreon Engine version**: 19.04.X

**Centreon Broker version**: 19.04.X

**OS**: Centreon ISO CentOS 7

**Steps to reproduce the issue:**
1. Set the event_queue_max_size parameters to 10 
2. Stop your mysql process 
3. Wait for some queue file to be created 
4. Start your mysql process

**Describe the results you received:**

With the following query you can spot that we insert same logs several times 

```SELECT * FROM centreon_storage.logs l1 join centreon_storage.logs l2 on l1.ctime = l2.ctime and l1.host_id = l2.host_id and l1.service_id = l2.service_id and l1.msg_type = l2.msg_type and l1.status = l2.status and l1.type = l2.type and l1.log_id != l2.log_id where l1.msg_type = 0 order by l1.host_name DESC, l1.service_description DESC \G```

Result 

```              log_id: 1278360
               ctime: 1568803586
             host_id: 24
           host_name: Centreon-Bdd
       instance_name: Remote-server
            issue_id: NULL
            msg_type: 0
    notification_cmd:
notification_contact:
              output: CRITICAL: Cannot connect: Can't connect to MySQL server on '10.30.X.X' (113 "No route to host")
               retry: 1
 service_description: Connection-Time
          service_id: 211
              status: 2
                type: 1
              log_id: 1278321
               ctime: 1568803586
             host_id: 24
           host_name: Centreon-Bdd
       instance_name: Remote-server
            issue_id: NULL
            msg_type: 0
    notification_cmd:
notification_contact:
              output: CRITICAL: Cannot connect: Can't connect to MySQL server on '10.30.X.X' (113 "No route to host")
               retry: 1
 service_description: Connection-Time
          service_id: 211
              status: 2
                type: 1
```

**Describe the results you expected:**

`Empty set (0.10 sec)
`

**Additional information you think important (e.g. issue happens only occasionally):**

Logs below might help to identify when the problem starts

```
[1568806157] error:   SQL: could not store service group membership (poller: 9, host: 299, service: 2344, group: 2): could not execute prepared statement: Duplicate entry '299-2344-2' for key 'host_id' QMYSQL3: Unable to execute statement
[1568806157] error:   SQL: could not store service group membership (poller: 9, host: 298, service: 2342, group: 2): could not execute prepared statement: Duplicate entry '298-2342-2' for key 'host_id' QMYSQL3: Unable to execute statement
```

**Comment by omercier** [comment]
@bouda1 we should close this issue, if I'm correct, it has been fixed in version 21.04.0.
