### ISSUE TITLE
Missing data in the stream connector

### ISSUE THREAD

**Issue by bouda1** [centreon/centreon-broker#313]
Here is an issue reported by @SomeAverageDev

In centreon "centreon-broker-3.0.16-1.el6.x86_64 / centreon-engine-1.8.1-1.el6.x86_64 / centreon-2.8.26-3.el6.noarch" (could be the root cause [edit:same thing with 2019.04]), I use the stream connector to get "category=1 & element=24" events (I filtered on "NEB" in broker configuration) I have defined an URL at "generic-service" level, the URL shows as expected in the CENTREON interface, but not in the LUA data.

Below a set of JSON data received by the "write" function:
 Mon 14 Oct 2019 05:27:18 PM CEST: INFO: DATA: {"acknowledgement_type":0,"check_attempt":3,"passive_checks":false,"last_state_change":1549633876,"next_check":1571067137,"should_be_scheduled":true,"flap_detection":true,"enabled":true,"host_id":19,"state":2,"last_update":1571066838,"last_check":1571066837,"execution_time":0.175196,"acknowledged":false,"service_id":43,"active_checks":true,"notify":false,"max_check_attempts":3,"obsess_over_service":true,"check_type":0,"last_hard_state_change":1549633876,"output":"Disk CRITICAL - no output (-p number expected... it doesn't exist, try another disk number)\n","category":1,"perfdata":"","check_interval":5,"check_command":"check_centreon_remote_storage!&quot","retry_interval":1,"check_period":"24x7","type":65560,"last_hard_state":2,"state_type":1,"percent_state_change":0,"notification_number":0,"event_handler":"","element":24,"checked":true,"no_more_notifications":false,"event_handler_enabled":true,"flapping":false,"scheduled_downtime_depth":0,"last_time_critical":1571066837,"last_time_unknown":1549633577,"latency":0.074} Mon 14 Oct 2019 05:27:18 PM CEST: INFO: *d.category = 1, d.element = 24*

**Comment by omercier** [comment]
These data are accessible in stream connectors thanks to the cache functions, now.
