### ISSUE TITLE
Encrypter la communication entre le Poller et le Central.

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon-broker#33]
Bonjour,

Après avoir posté sur le forum et de ne pas avoir eu de réponse satisfaisante à mes questions, je décide d'ouvrir un issue car je suis certain que d'autres utilisateurs ont les mêmes questions que moi.
La documentation pour encrypté la communication entre le Poller et le Central n'est pas du tout claire à mon avis.

La documentation est situé à l'adresse https://documentation.centreon.com/docs/centreon-broker/en/latest/user/modules.html#tls

Est-ce que l'on peut utiliser un certificate self sign ?
Est-ce que l'on doit absolument configuré Trusted CA certificate ?

J'ai créer un certificat self sign en suivant une procédure fiable.
J'ai copié le certificat et la clé dans /etc/pki/tls/certs et /etc/pki/tls/private sur chacun des Poller et sur le Central mais quand je restart le Poller, j'ai cette erreur:
error: TLS: could not load certificate: Error while reading file.
error: TLS: could not load certificate: Error while reading file.
error: TLS: could not load certificate: Error while reading file.
error: TLS: could not load certificate: Error while reading file.
error: TLS: could not load certificate: Error while reading file.

Voici ma configuration:
http://imgur.com/UblASc9

Qu'est-ce qui ne fonctionne pas ?

Je crois que ces informations devraient être inclue dans la documentation.

Merci pour votre habituelle compréhension et coopération.

Sébastien

**Comment by joschi99** [comment]
I have the same error on Centreon Broker 3.0.3.

**Comment by ganoze** [comment]
I've juste updated the TLS module documentation. Could you check it out at https://github.com/centreon/centreon-broker/blob/master/doc/user/modules.rst ?

I voluntarily do not provide more information in this comment so that I can ensure that the documentation is complete. In all cases, let me know :-)

**Comment by sboulianne** [comment]
Thanks you very much for updating the doc.
Is it possible for you to write some doc about how to implent it/config it in Centreon ?

Thanks in advance.

**Comment by sboulianne** [comment]
Thanks for updating the doc but it won't explain how to setup.
Can you include a how to tuto ?
Thanks.

**Comment by sboulianne** [comment]
also, please reopen this pull request since its not 100% completed.

**Comment by ganoze** [comment]
Documentation was added to Centreon Web in PR 5614 (https://github.com/centreon/centreon/pull/5614).

I'm closing this ticket now, documentation will be released as part of Centreon Web 2.8.13.
