### ISSUE TITLE
The CRSF token is invalid

### ISSUE THREAD

**Issue by Eldertoon** [centreon/centreon-broker#35]
I updated to CES 2.6.5. Since then, when I try to do multi tab operation (in Firefow) I get this error. For example :
- open two services (one per tab)
- click in each tab on "Submit downtime"
- in the lanst opened one, enter all information and set the downtime : it works
- on the other, enter all information and set the downtime : it fails with this error

In fact, only the last opened tab works, all other tab will fail. This also happen when trying to modify configuration on services with multiple tab : only the last opened one will not display the error (but in configuration, the error has a save button beside to retry and then it works).

This was not existing in CES 2.6.4.

This is a big issue on the monday morning when I set downtime for all services in maintenance (my best practice is to have no downtime longer than a week).

**Comment by Dacchi** [comment]
Hi, we are aware of this issue.
It has been fixed and will be release in Centreon 2.6.6.
