### ISSUE TITLE
Broker + plugin Graphite beta: variables $xxx$ vides

### ISSUE THREAD

**Issue by GrinGrin** [centreon/centreon-broker#38]
Bonjour,
Je viens d'installer et configurer le dernier package du plugin disponible dans le repo Centreon (centreon-broker-cbd-2.10.1-6.el6.x86_64 + centreon-broker-graphite-2.10.1-6.el6.x86_64) et j'arrive à envoyer des données à mon instance Carbon locale.

Le seul problème rencontré pour l'instant est que les variables comme *$INSTANCE$*, *$HOST$*, *$SERVICE$*, ... restent vide.

J'utilise cette configuration dans mon fichier central-broker.xml:
```xml
<output>
  <name><![CDATA[centreon-broker-master-graphite]]></name>
  <type><![CDATA[graphite]]></type>
  <db_host><![CDATA[localhost]]></db_host>
  <db_port><![CDATA[2003]]></db_port>
  <db_user><![CDATA[carbon]]></db_user>
  <metric_naming><![CDATA[centreon.metrics.$HOST$.$SERVICE$.$METRIC$]]></metric_naming>
  <status_naming><![CDATA[centreon.statuses.$HOST$.$SERVICE$]]></status_naming>
</output>
```

Tout ce que je vois dans le log de l'instance carbon c'est:
`20/11/2015 22:59:22 :: creating database file /var/lib/carbon/whisper/centreon/metrics///cpu1>.wsp (archive=[(60, 1440)] xff=None agg=None)`
Rien de plus utile dans le debug de cbd (cbd -d /etc/centreon-broker/central-broker.xml):
`[1448055112] debug:   graphite: commiting 1 queries`

Si je ne configure pas les metric_naming et status_naming, la valeur par défaut comme indiquée dans la documentation est utilisée avec seulement l'ID du metric:
`20/11/2015 23:05:08 :: creating database file /var/lib/carbon/whisper/centreon/metrics/671.wsp (archive=[(60, 1440)] xff=None agg=None)`

J'utilise ce plugin pour tester un dashboard Grafana et pour l'instant je dois consulter la base Centreon pour pouvoir déterminer pour un hote donné l'ID du metric que je souhaite utiliser dans les requêtes Grafana: 
![2015-11-20_23h25_42](https://cloud.githubusercontent.com/assets/15949215/11313550/0b9f1810-8fde-11e5-802a-4da6d9fdfeb4.png)
La même problématique se présente aussi avec Graphite-web qui me présente juste la liste des ID de metrics:
![2015-11-20_23h27_00](https://cloud.githubusercontent.com/assets/15949215/11313584/38971638-8fde-11e5-99e9-b38d6f8e93d7.png)

Je sais qu'il s'agit d'un plugin en beta, mais cette extension serait un sérieux plus en complément du dashboard actuel de Centreon pour utiliser sur des écrans de contrôle type TV.

Cordialement,
Nicolas.

**Comment by afouille** [comment]
Bonjour,

Les seules macros acceptées par l'output Graphite de Centreon Broker 2.x sont $INSTANCEID$, $METRIC$, $INDEXID$, et $METRICID$. Cela est dû à une limitation inhérente au cœur de la version 2.x de Broker. L'ensemble des macros sont bien supportées par la prochaine version majeur 3.x de Broker, qui sortira dans les prochains mois.

Cette limitation aurait dû être bien expliquée dans la documentation. J'ai vérifié et ce n'est pas le cas, je le changerai lundi.

Cordialement,
Alexandre.
