### ISSUE TITLE
Missing graphs for new services / metrics are not build

### ISSUE THREAD

**Issue by lunze** [centreon/centreon-broker#39]
Hi together,

i am using the following installation:

- Centreon 2.6.6
- Centreon-Clib 1.4.2
- Centreon-Engine 1.4.15
- Centreon-Broker 2.10.1

The problem manifests itself as follows:

For all my existing services centreon-broker stores the performance-data in the database and creates successfully some rrd-graphs.
If i duplicate a service or create a completely new one, then export the config and restart the centreon-engine via the web-interface, the new services will be displayed in the web, but no graphs appear.

After this i read the documentation about graph managing with the help of centreon-broker.
Now i know the normal behaviour should be this:

Centreon inserts the index_data in database for all new objects and the centreon-broker creates the metric_data at the moment it receives some performance-data and stores the informations in the data_bin table for later rebuilding.

In my situation centreon creates the index_data but the broker did not create any metrics.
Thats why there are no graphs to show.
After i restart the broker it creates all missing metrics, stores new performance-data and creates rrd-graphs.

My question now, is there any new configuration step i have missed?
Or why centreon-broker didn't create metrics without restart.
With the old constellation (i am not sure, i think it was the following: centreon-2.6.1, clib-1.4.2, engine-1.4.13, broker-2.8.2) it works without restart of the broker.

If you need any more informations from me, let me know it.
I would be delighted to hear from you.

With nice regards
Martin Lunze

**Comment by ganoze** [comment]
Once inserted in *index_data*, Centreon Broker needs to be aware that new entries have been inserted. For this purpose, you need to reload the Centreon Broker daemon (either through init.d script or by sending a SIGHUP signal). According to your explanations that is probably the mising step, as a restart of Centreon Broker (that will make it read the *index_data* table again) make metrics appear.

Let me know if this solve your problem.

**Comment by ganoze** [comment]
Timeout.
