### ISSUE TITLE
Problème de requête très grosse vers data_bin

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#41]
Au moment de la sortie de retention, des grandes requêtes sont envoyés vers la base de données la mettre à jour et provoque des problèmes lié à la variable max_allowed_packet de MySQL. 

Quand je regarde la fonction "void stream::_insert_perfdatas()". Je m'aperçois qu'une condition boucle while est positionné comme ceci : while (!_perfdata_queue.empty()) { 

Je pense qu'il serait mieux de faire des requêtes SQL beaucoup moins grosse (Donc moins longue en temps d'excution) et de pouvoir configurer au mieux MySQL, être sûr que les requêtes vont passer. 

Type d'erreur que cela provoque : "error: storage: could not insert data in data_bin: could not execute query: MySQL server has gone away QMYSQL: Unable to execute query (INSERT INTO data_bin (id_metric, ctime, status, value) VALUES [...]"

Je me permet aussi, de dire, qu'après ce type d'erreur. Je suis obligé de redemarrer centreon-broker car centreon essai d'envoyer des requêtes vers le serveur BDD, même si le serveur réplique avec des RESET.

Cordialement.

**Comment by ganoze** [comment]
Bonjour et merci pour votre retour :-)

Ce comportement est fait de manière à optimiser les performances sur l'insertion des données de performance dans data_bin. En effet chez la majorité de nos clients cette table est en MyISAM est les INSERT multi-values sont donc le moyen le plus rapide de stocker les données.

À moyen terme ce comportement est amené à évoluer car depuis la 2.7 cette table est installée par défaut en InnoDB. Nous utiliserons donc dans le futur le système que nous avons pour les autre tables, à savoir une transaction avec des requêtes préparées.

Pour contourner votre problème vous pouvez diminuer le paramètre *Maximum queries per transaction* de l'output *central-broker-master-perfdata* situé dans le fichier de configuration Broker *central-broker-master*. Ceci limitera le nombre de valeurs utilisées dans une seule requête.

**Comment by jben94** [comment]
Bonjour,

Merci pour le conseil, je ne pensais pas que ce paramètre pouvait jouer avec le nombre de donnée envoyée en une seul requête SQL. J'avais compris que le paramètre permettait de limité juste le nombre de requête SQL envoyé par commit.

Je viens de regarder la requête SQL reçu par mysql lors de notre problème. La requête à 320 000 valeurs et le paramètre que vous m'avez indiqué est positionné à 20 000. 
Donc j'ai un doute sur le bon fonctionnement du paramètre.

**Comment by ganoze** [comment]
Il faut plus prendre le paramètre comme une indication relative. En effet ce paramètre se base en fait sur le nombre de résultats de checks traités. Si un check contient plusieurs métriques alors le nombre de valeurs insérées est multiplié d'autant.

En revanche si vous divisez le paramètre par deux, le nombre de valeurs utilisées dans la requête sera lui aussi divisé par deux.

**Comment by jben94** [comment]
Bonjour,
Merci pour cette indication.

**Comment by sgaudart** [comment]
Hello,

J'ai eu le soucis récemment mais pas pour la table data_bin mais pour la table logs.
J'ai trouvé un workaround en faisant : changer (coté mysq) la valeur max_allowed_packet=16M (ou autre chose selon votre conf) coté my.cnf
Source :
http://stackoverflow.com/questions/7942154/mysql-error-2006-mysql-server-has-gone-away
