### ISSUE TITLE
Erreur de calcul - 5 minutes

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#42]
Bonjour,

Le calcul des 5 minutes me pareil non correcte, dans la fonction "creator::create".
5 * 60 * 60 > 5 * 60 ?

Cordialement.

**Comment by ganoze** [comment]
Fixed in commit 67069159d39b6e394cf841341d0cadbb6a45ad97.

**Comment by ganoze** [comment]
BTW, thank you very much for your report.
