### ISSUE TITLE
Committed secret

### ISSUE THREAD

**Issue by OriPekelman** [centreon/centreon-broker#439]
### Description

In 
https://github.com/centreon/centreon-broker/blob/master/lua/anomaly-detection/centreon-anomaly-detection.lua#L63
you have 
```
  token = "tRGkO5tjVA2qHOYfgKkY21SoTYPNif6ualYmeBpm",
```
Which on its face looks like a secret committed to git. If this is not actually a secret I believe it is in order to add a comment and explain why this is not a secret, such as that the next person around won't be alarmed.

If it is a secret it should probably move out of code to secret management facility, configuration or the environment and potentially the secret should be rotated.

**Comment by bouda1** [comment]
Usually, the data block at the beginning of the stream connector is a block of data.
We provide data in it to give examples, but usually those data are overwritten by the user configuration.
Now, I hope I'm right and that is only an example. :smiley: @lpinsivy What's your opinion?

**Comment by lpinsivy** [comment]
Yes it's a token example.

Regards,
