### ISSUE TITLE
Wrong input, rrd not working anymore

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon-broker#44]
Hello Guys,

i used a plugin in centreon-engine that was not really good. But thanks to that, maybe i found a problem. That script created perf-data with text instead of numbers. The RRD Graph was not working then. After fix the connection, and perf-data was number and not text, graph came back.

It should not be possible to input text right?

**Comment by afouille** [comment]
Hi,

Was all the graphs affected, or only the one concerned by the plugin in question? If your plugin returns non plottable metrics, then it is normal if the graph doesn't show.

**Comment by florian-asche** [comment]
Hi, only the one where the plugin created text in perf-data area. But i think if only numbers work in rrd, a filter before all that goes into database whould be great.

**Comment by ganoze** [comment]
Fixed in commit 8ec3c4399523adf6938625ffe0441cc823f9d527.

**Comment by florian-asche** [comment]
Great!

**Comment by ganoze** [comment]
Centreon Broker 3.0.6 is now released.
