### ISSUE TITLE
core dump cbd

### ISSUE THREAD

**Issue by Rico29** [centreon/centreon-broker#441]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***
root@morgol:/var/log# rpm -qa | grep centreon
centreon-widget-engine-status-20.04.1-1.el7.centos.noarch
centreon-widget-global-health-20.04.0-5.el7.centos.noarch
centreon-license-manager-common-20.04.2-1.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20200602-094050.el7.centos.noarch
centreon-broker-20.04.6-3.el7.centos.x86_64
centreon-widget-hostgroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-database-20.04.4-6.el7.centos.noarch
centreon-broker-graphite-20.04.6-3.el7.centos.x86_64
centreon-widget-servicegroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20200602-094050.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20200602-094050.el7.centos.noarch
centreon-connector-ssh-20.04.0-2.el7.centos.x86_64
centreon-engine-daemon-20.04.4-1.el7.centos.x86_64
centreon-poller-centreon-engine-20.04.4-6.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20200410-101650.el7.centos.noarch
centreon-clib-20.04.0-7.el7.centos.x86_64
centreon-widget-live-top10-cpu-usage-20.04.0-5.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20200602-094050.el7.centos.noarch
centreon-common-20.04.4-6.el7.centos.noarch
centreon-broker-core-20.04.6-3.el7.centos.x86_64
centreon-widget-service-monitoring-20.04.2-1.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20200602-094050.el7.centos.noarch
centreon-engine-extcommands-20.04.4-1.el7.centos.x86_64
centreon-broker-cbd-20.04.6-3.el7.centos.x86_64
centreon-auto-discovery-server-20.04.3-3.el7.centos.noarch
centreon-widget-grid-map-20.04.0-5.el7.centos.noarch
centreon-widget-httploader-20.04.0-5.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20200602-094050.el7.centos.noarch
centreon-connector-perl-20.04.0-2.el7.centos.x86_64
centreon-widget-tactical-overview-20.04.0-5.el7.centos.noarch
centreon-release-20.04-1.el7.centos.noarch
centreon-perl-libs-20.04.4-6.el7.centos.noarch
centreon-gorgone-centreon-config-20.04.3-1.el7.centos.noarch
centreon-engine-20.04.4-1.el7.centos.x86_64
centreon-base-config-centreon-engine-20.04.4-6.el7.centos.noarch
centreon-20.04.4-6.el7.centos.noarch
centreon-broker-devel-20.04.6-3.el7.centos.x86_64
centreon-widget-live-top10-memory-usage-20.04.0-5.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200602-094050.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200602-094050.el7.centos.noarch
centreon-gorgone-20.04.3-1592227842.c77e2d5.el7.centos.noarch
centreon-broker-cbmod-20.04.6-3.el7.centos.x86_64
centreon-widget-host-monitoring-20.04.3-2.el7.centos.noarch
centreon-broker-debuginfo-20.04.6-3.el7.centos.x86_64
centreon-license-manager-20.04.2-1.el7.centos.noarch
centreon-widget-graph-monitoring-20.04.0-5.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20200602-094050.el7.centos.noarch
centreon-connector-20.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Dns-20200602-094050.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20200602-094050.el7.centos.noarch
centreon-pp-manager-20.04.1-1.el7.centos.noarch
centreon-broker-storage-20.04.6-3.el7.centos.x86_64
centreon-trap-20.04.4-6.el7.centos.noarch
centreon-web-20.04.4-6.el7.centos.noarch
centreon-broker-influxdb-20.04.6-3.el7.centos.x86_64

***Operating System***

root@morgol:/var/log# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
root@morgol:/var/log# uname -a
Linux morgol 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

***How the the component has been installed and versions***

from packages

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

core dumps of cdb.
errors in central-broker-master.log :

```
...
[1594371140] config:  endpoint applier: new filtering element: 393224
[1594371140] config:  endpoint applier: new filtering element: 65558
[1594371140] config:  endpoint applier: new filtering element: 65550
[1594371140] config:  endpoint applier: creating new endpoint 'central-broker-master-perfdata'
[1594371140] error:   expected ':' in object, got 's' (115)
[1594371146] error:   mysql: Error while sending prepared query: Incorrect string value: '\xE2\x97_ ls...' for column `centreon_storage`.`logs`.`output` at row 1 (SQL: )
[1594371146] error:   conflict_manager: error in the main loop: could not prepare insert or update query for event 'host' in table 'rt_hosts': Incorrect string value: '\xE2\x97_ ls...' for column `centreon_storage`.`logs`.`output` at row 1 (while executing statement 2075038481)
[1594371146] error:   conflict_manager: error while checking deleted indexes: could not query index table to get index to delete: 
[1594371199] error:   conflict_manager: events loop interrupted
```

### Steps to Reproduce
N/A

### Describe the received result
core dumps and all remote pollers unreachable

### Describe the expected result
no core dumps and pollers reachable :)

### Logs
see above

**PHP error logs**
non relevant
```
tail -f /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log
[10-Jul-2020 07:45:25 Europe/Paris] PHP Notice:  Undefined index: current in /usr/share/centreon/www/install/step_upgrade/process/process_step5.php on line 77

```
**centreon-engine logs (*if needed*)**

```
tail -f /var/log/centreon-engine/centengine.log
```
**centreon-broker logs (*if needed*)**

```
tail -f /var/log/centreon-broker/central-broker-master.log
[1594371140] config:  endpoint applier: new filtering element: 393224
[1594371140] config:  endpoint applier: new filtering element: 65558
[1594371140] config:  endpoint applier: new filtering element: 65550
[1594371140] config:  endpoint applier: creating new endpoint 'central-broker-master-perfdata'
[1594371140] error:   expected ':' in object, got 's' (115)
[1594371146] error:   mysql: Error while sending prepared query: Incorrect string value: '\xE2\x97_ ls...' for column `centreon_storage`.`logs`.`output` at row 1 (SQL: )
[1594371146] error:   conflict_manager: error in the main loop: could not prepare insert or update query for event 'host' in table 'rt_hosts': Incorrect string value: '\xE2\x97_ ls...' for column `centreon_storage`.`logs`.`output` at row 1 (while executing statement 2075038481)
[1594371146] error:   conflict_manager: error while checking deleted indexes: could not query index table to get index to delete: 
[1594371199] error:   conflict_manager: events loop interrupted
```
**centcore logs (*if needed*)**

```
tail -f /var/log/centreon/centcore.log
```

### Additional relevant information (e.g. frequency, ...)
I will attach a coredump following https://github.com/centreon/centreon/wiki/Technical-FAQs#generate-a-core-dump

**Comment by Rico29** [comment]
```
Fri 2020-07-10 10:23:10 CEST  11161   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:25:11 CEST  11871   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:27:11 CEST  12592   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:29:10 CEST  13344   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:31:10 CEST  14070   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:33:12 CEST  14823   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:36:16 CEST  15545   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:38:14 CEST  16626   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:40:14 CEST  17385   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:42:15 CEST  18118   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:45:17 CEST  18880   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:47:18 CEST  19962   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:49:18 CEST  20720   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:51:18 CEST  21436   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:53:19 CEST  22184   996   994   6 * /usr/sbin/cbd
Fri 2020-07-10 10:55:20 CEST  23307   996   994   6 * /usr/sbin/cbd
```

core dump available at http://dl.celya.fr/cbd.core

**Comment by bouda1** [comment]
We have found an issue that looks like yours. I will try to fix it next week.
Thank you.

**Comment by Syll-GH** [comment]
Exactement le même problème. Impossible de mettre à jour ma version 20.04 sans avoir les mêmes erreurs dans les logs

> tail -f /var/log/centreon-broker/central-broker-master.log
> [1594628009] error:   conflict_manager: error in the main loop: Incorrect string value: '\xE2\x80\xE2\x84\xA2a...' for column `centreon_storage`.`logs`.`output` at row 1 (while executing statement 2075038481)
> [1594628009] error:   conflict_manager: error while checking deleted indexes: could not query index table to get index to delete:
> [1594628010] error:   conflict_manager: events loop interrupted
> [1594628010] error:   conflict_manager: events loop interrupted
> [1594628071] error:   conflict_manager: error in the main loop: Incorrect string value: '\xE2\x80\xE2\x84\xA2a...' for column `centreon_storage`.`logs`.`output` at row 1 (while executing statement 2075038481)
> [1594628071] error:   conflict_manager: error while checking deleted indexes: could not query index table to get index to delete:
> [1594628072] error:   conflict_manager: events loop interrupted
> [1594628072] error:   conflict_manager: events loop interrupted

**Comment by Rico29** [comment]
fixed it for now by downgrading, following https://docs.centreon.com/current/en/releases/centreon-core.html#20045

**Comment by Syll-GH** [comment]
Next update to 20.04.6, the problem come back again...

**Comment by bouda1** [comment]
The bug is not in centreon-broker but in centreon-engine.
Checks are made by centreon-engine. It receives check outputs that are usually utf-8 encoded strings. But sometimes, with several checks running on windows for example, are encoded in CP1252.
The last patch provided on centreon-engine tried to convert strings in a such encoding to utf-8, so that broker can store the resulting string.
The bug you encounter is that the utf-8 validator in Engine is not strict enough. Some bad strings could pass through the test.
The new branch MON-5737-encoding2 fixes this bad validator.

We have still one issue that I must check with concerned people. Sometimes, checks return to centreon-engine outputs containing a csv file. If they are built from a Windows host, those file may contain a BOM prefix. and that can also cause centreon-engine to not correctly interpret the string. This last point is not fixed at the moment, still working on it.

**Comment by Rico29** [comment]
Hello,
Any news ?

**Comment by bouda1** [comment]
There is a fix in centreon-engine that should fix your issue. Waiting now
for its integration and release. Regards.

**Comment by bouda1** [comment]
I have changed a little the fix so that it is easier to update. We had to remove retention files, and other ones before restarting engine/broker. Now the procedure should be quite simpler. The patch concerns engine and broker this time. See #446 

Should be released soon :crossed_fingers:
