### ISSUE TITLE
Set comments expire_time to NULL when not set

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon-broker#47]
In the database comments have their _expire_time_ set to 0 when they are not set. However they should be set to NULL.

**Comment by julienmathis** [comment]
This problem impact centreon sql install file ?

**Comment by ganoze** [comment]
Nope, this is only related to how Centreon Broker process *expire_time* when set to 0. Centreon already install the table with the default NULL attribute, so no problem on this side.

**Comment by ganoze** [comment]
Fixed in an already released version of Centreon Broker.
