### ISSUE TITLE
[retention] Grows very fast

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon-broker#5]
Comment of Quentin Garnier:

When you have many checks with some big outputs (long_msg), retention files for perfdata generator output grows very fast (even with neb filter only). I thin there is all datas on it no ? Could be possible to have only useful datas (perfdatas) ? We'll save some many spaces on disk (and parsing we'll faster also i think).

**Comment by ganoze** [comment]
In Centreon Broker 3, retention files will be compressed and unused data (as per filters) will be discarded, heavily reducing the size of the forementioned files.

**Comment by florian-asche** [comment]
If you change "Maximum queries per transaction" from 5000 or 20.000 to 50 on all sql Outputs, it is a lot faster.
