### ISSUE TITLE
cbd-est-mort-mais-le-fichier-pid-existe

### ISSUE THREAD

**Issue by chrisjouin** [centreon/centreon-broker#51]
Bonjour,

J'utilise la dernière version de Centreon 2.7.4 et après import via CLAPI et configuration des objets et services je me rend compte que l'état du service cbd est incorrecte "cbd-est-mort-mais-le-fichier-pid-existe" même après un redémarrage du service et re compilation.
La supervision a l'air fonctionnelle pour autant.

Le fichier central-module-master.log contient : 

Centreon Broker 2.11.4 log file opened
config:  log applier: applying 1 logging objects
config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
config:  correlation: invalid correlation configuration, correlation engine is NOT loaded
error:   TCP: could not connect to localhost:5669: Connection refused
error:   TCP: error while sending data to peer 'localhost:5669': The remote host closed the connection
Centreon Broker 2.11.4 log file closed

J'ai mis en pièce jointe les fichiers de log : 

[central-broker-master.log.txt](https://github.com/centreon/centreon-broker/files/277489/central-broker-master.log.txt)
[central-module-master.log.txt](https://github.com/centreon/centreon-broker/files/277491/central-module-master.log.txt)
[central-rrd-master.log.txt](https://github.com/centreon/centreon-broker/files/277492/central-rrd-master.log.txt)

Est ce que l'un d'entre vous pourrait m'aider svp?
Merci par avance.

**Comment by sensemila** [comment]
Bonjour, 

Peux tu me montrer le résultat de cette commande ? 

/usr/local/centreon-broker/bin/cbd -c '/usr/local/centreon-broker/etc/central-broker.xml'

Cordialement

**Comment by chrisjouin** [comment]
J'ai effacé entièrement ma config (hosts, services, templates, commandes...) puis j'ai ré édité mon fichier d'import en retirant les configurations déjà présente puis recompiler. Depuis les service cbd et la console sont opérationnels.
