### ISSUE TITLE
centreon broker is not running

### ISSUE THREAD

**Issue by phoppe93** [centreon/centreon-broker#53]
Hi, 

the centreon broker ist crashed after starting.

15.06.2016 11:19:38: cleanup ended with RC=0.
INFO    - Special pre command ended with RC=0
Starting cbd_central-broker-master:                        [  OK  ]
Starting cbd_central-rrd-master:                           [  OK  ]
INFO    - Waiting for server to come up...
INFO    - Sleeping for 10 seconds

please check the logfile.

[centreon_broker_strace.txt](https://github.com/centreon/centreon-broker/files/316448/centreon_broker_strace.txt)

**Comment by ganoze** [comment]
There seems to be an error printed in Centreon Broker log file. Could you take a look at it ?

**Comment by phoppe93** [comment]
Hi ganoze, i resolved the problem.

Thanks for yout time.

the broker configuration was wrong.

**Comment by ganoze** [comment]
Thank you for your report. Have a nice day.
