### ISSUE TITLE
[BROKER 3.0.0]One retention file create at lunch

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon-broker#56]
With broker 3.0.0 one retention file of 8 Byte is create '/var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention'

If you stop broker, erase this file and start broker. It will created again

**Comment by ganoze** [comment]
Indeed there is an issue. When the initialization of the base endpoint is very fast (RRD for instance), the failover thread do not get a chance to provide its events. For the RRD endpoint this only means that the retention file does not get deleted but this could lead to much bigger issues : in case of weird thread scheduling delays the retention events of any endpoint could be unprocessed !

Thank you for pointing it out.
