### ISSUE TITLE
[metrics] delete absent/empty metrics

### ISSUE THREAD

**Issue by fpeterschmitt** [centreon/centreon-broker#60]
Hello again,

I'm not sure it's about `centreon-broker` but since it's this component that insert data, i think it should take care of data cleanup.

I got some empty/broken graphs in the split graph view, and discovered that it pointed to a valid `metric` entry, but without any data in `data_bin`. Those metrics were simply not updated for too long and associated data were cleaned-up.

SQL query to cleanup:

``` sql
delete from metrics where (select count(*) from data_bin as db where db.id_metric=metric_id) = 0;
```

**Comment by bouda1** [comment]
This issue is pretty old. I close it. If you still see it with last version of broker, could you reopen it in the centreon-collect repo.

Thanks.
