### ISSUE TITLE
Issues with make in 21.04.x version

### ISSUE THREAD

**Issue by EtienneN10** [centreon/centreon-broker#610]
Hello,

When I compile using make, I get this error : 

`/usr/bin/ld: reflection.pb.cc:(.text+0x4d24): undefined reference to ``google::protobuf::internal::VerifyUTF8(google::protobuf::stringpiece_internal::StringPiece, char const*)`

Do you know how I can set it? 

Thanks in advance

**Comment by omercier** [comment]
`reflection.pb.cc` has been removed since then.
