### ISSUE TITLE
RRD step is wrong

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon-broker#62]
Hello,

I changed my "Interval Length" in the page "Administration --> Parameters --> Monitoring" from 60 seconds to 1 second.
In my service configuration, I define a "normal check interval" to 600.

My service is now checked every 10 minutes (600 seconds) but my graph as a new point every 10 hours.

When I use rrdtool command on a curve, I have a step of 36000 (it must be 600) .

> **# rrdtool info /var/lib/centreon/metrics/4071.rrd**
> filename = "/var/lib/centreon/metrics/4071.rrd"
> rrd_version = "0003"
> step = 36000
> last_update = 1470669204
> header_size = 792
> ds[value].index = 0
> ds[value].type = "GAUGE"
> ds[value].minimal_heartbeat = 360000
> ds[value].min = NaN
> ds[value].max = NaN
> ds[value].last_ds = "1.099000"
> ds[value].value = 1,8353000000e+01
> ds[value].unknown_sec = 33187
> rra[0].cf = "AVERAGE"
> rra[0].rows = 433
> rra[0].cur_row = 315
> rra[0].pdp_per_row = 1
> rra[0].xff = 5,0000000000e-01
> rra[0].cdp_prep[0].value = NaN
> rra[0].cdp_prep[0].unknown_datapoints = 0
> rra[1].cf = "AVERAGE"
> rra[1].rows = 37
> rra[1].cur_row = 12
> rra[1].pdp_per_row = 12
> rra[1].xff = 5,0000000000e-01
> rra[1].cdp_prep[0].value = NaN
> rra[1].cdp_prep[0].unknown_datapoints = 3

Centreon-broker 2.11.5
Centreon 2.7.6

regards,

**Comment by afouille** [comment]
Hi,

Fixed in the branch interval_length. Pending an acceptation in Broker 3.0.

Regards,

**Comment by ludovicgrondin** [comment]
Hello,

I encounter the same problem with Centreon-broker 3.0.3.

Do you know if this issue have been fixed?

Regards,
