### ISSUE TITLE
CBD crash after poller restart

### ISSUE THREAD

**Issue by kom0do** [centreon/centreon-broker#63]
Hi,

since last update cbd is crashing when i restart some poller.
Poller reload is ok, but when i stop poller, then cbd crash.

Here is coredump from last crash.

ftp://ftp.bosson.eu/pub/tmp/core.cbd.26133

OS is Centos 6.8 and cbd is from CES repo
2.11.5-2.el6

**Comment by kom0do** [comment]
Hi, something new ?
It's really annoying, now i have cron job for checking and starting cbd if it's not running, but it's not solution.

**Comment by ganoze** [comment]
Thank you very much for the core dump file. This really helped in finding out where the error came from. There seemed to be an issue when TCP streams are getting closed too fast. This generates an uncaught error which terminates the daemon.

I was not able to reproduce it myself but hopefully the upcoming commit will fix your problem.

**Comment by joschi99** [comment]
I have a similar problem on our poller after upgrading to centreon-broker 3.0.1 on CentOS 6.8. The broker service is always crashing and restarting continuously.

watchdog log shows:
`[1480637452] error:   watchdog: process 'central-broker' has terminated unexpectedly, restarting it in 1 seconds`
`[1480637453] info:    watchdog: starting process 'central-broker'`

Same error like above or a new case?
