### ISSUE TITLE
Centreon Broker libqt4.7 dependency

### ISSUE THREAD

**Issue by reizer-fs** [centreon/centreon-broker#66]
Hello,

All Centreon Broker version (up to 2.11.5) need at least QT 4.7.4 in order to be compiled.

I sucessfully compiled Centreon Engine without any QT libs, but i could'nt compile Broker since no QT libs > 4.6.x. on SUSE Entreprise Server 11.

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Qt4: Found unsuitable version "4.6.3", but required is at
  least "4.7.4" (found /usr/bin/qmake)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindQt4.cmake:1393 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:45 (find_package)

Maybe a workaround exists ?

Regards,

**Comment by ganoze** [comment]
Thank you for your message. Unfortunately there is no workaround, as all versions of Qt < 4.7.4 have bugs that prevent Centreon Broker from working properly. As such, the basic options to make it work on your system would be to either compile Qt yourself or find existing packages of Qt >= 4.7.4 for your system.
