### ISSUE TITLE
Centreon Broker Compilation

### ISSUE THREAD

**Issue by reizer-fs** [centreon/centreon-broker#67]
Hello, when compiling Centreon Broker 2.11.5
I get the following error : 

make
[ 20%] Built target rokerbase
[ 20%] Built target roker
[ 20%] Built target cbd
[ 23%] Built target 15-stats
[ 33%] Built target nebbase
[ 33%] Built target 10-neb
[ 45%] Built target cbmod
[ 46%] Built target 50-file
[ 47%] Built target 60-compression
[ 50%] Built target 20-correlation
[ 55%] Built target 05-dumper
[ 58%] Built target 70-rrd
[ 61%] Built target 80-sql
[ 65%] Built target 20-storage
[ 67%] Built target 70-influxdb
[ 68%] Built target 70-graphite
[ 88%] Built target 20-bam
[ 91%] Built target 50-tcp
[ 91%] Building CXX object tls/CMakeFiles/60-tls.dir/usr/local/centreon-broker-2.11.5/centreon-broker-2.11.5/tls/src/internal.cc.o
/usr/local/centreon-broker-2.11.5/centreon-broker-2.11.5/tls/src/internal.cc: In function âvoid com::centreon::broker::tls::initialize()â:
/usr/local/centreon-broker-2.11.5/centreon-broker-2.11.5/tls/src/internal.cc:107: error: âGNUTLS_VERSIONâ was not declared in this scope
make[2]: **\* [tls/CMakeFiles/60-tls.dir/usr/local/centreon-broker-2.11.5/centreon-broker-2.11.5/tls/src/internal.cc.o] Error 1
make[1]: **\* [tls/CMakeFiles/60-tls.dir/all] Error 2
make: **\* [all] Error 2
# cmake --version

cmake version 2.8.12.1
# qmake --version

QMake version 2.01a
Using Qt version 4.8.6

OS SLES 11.4 (Suse Linux Entreprise Server SP4)

It refers to this part : 
// Log GNU TLS version.
  {
    logging::info(logging::medium)
      << "TLS: compiled with GNU TLS version " << GNUTLS_VERSION;
    char const\* v(gnutls_check_version(NULL));
    if (!v)
      v = "unknown";
    logging::info(logging::high)
      << "TLS: loading GNU TLS version " << v;
  }

So I checked gnutls libs : 
# rpm -qa libgnutls-devel

libgnutls-devel-2.4.1-24.39.60.1

And libgcrypt:
# rpm -qa libgcrypt11

libgcrypt11-1.5.0-0.19.1

Any idea on what is going on ?

Regards,

**Comment by ganoze** [comment]
Well it seems like your GnuTLS version is too old to contain the GNUTLS_VERSION macro. Replacing it with LIBGNUTLS_VERSION should help you compile Centreon Broker. However you might run into other compilation issues or maybe runtime bugs. So be careful.

The documentation currently states that only GnuTLS >= 2.0 versions are needed. I will upgrade this requirement to >= 2.8.

**Comment by reizer-fs** [comment]
Hi,

Danke, replacing GNUTLS_VERSION macro by LIBGNUTLS_VERSION helped.
Compilation is now successful and give no more errors.

Regards,
