### ISSUE TITLE
Pas de Graphs depuis Import

### ISSUE THREAD

**Issue by nikitito** [centreon/centreon-broker#69]
Bonjour à tous,

voici mon problème sur lequel je bloque depuis le début de semaine et je n'arrive pas à trouver d'où cela viens...
Semaine dernière, j'ai par erreur supprimer mes 3 collecteurs de la plateforme, en essayant de les rajouter à la mano ils étaient impossible à démarrer, j'ai donc fait un import de toute la conf ( j'ai tous les jours un full_export ) et restaurer certains fichiers que voici :
`filesGeneration/nagiosCFG/6:
total 132
-rw-r--r-- 1 apache centreon 4208 Oct 15 10:45 centengine.cfg
-rw-r--r-- 1 apache centreon 5299 Oct 15 10:45 commands.cfg
-rw-r--r-- 1 apache centreon 1662 Oct 15 10:45 connectors.cfg
-rw-r--r-- 1 apache centreon 2175 Oct 15 10:45 contactgroups.cfg
-rw-r--r-- 1 apache centreon 12709 Oct 15 10:45 contacts.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 dependencies.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 escalations.cfg
-rw-r--r-- 1 apache centreon 3972 Oct 15 10:45 hostgroups.cfg
-rw-r--r-- 1 apache centreon 6313 Oct 15 10:45 hosts.cfg
-rw-r--r-- 1 apache centreon 4270 Oct 15 10:45 hostTemplates.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_commands.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_host.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_services.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_timeperiod.cfg
-rw-r--r-- 1 apache centreon 4712 Oct 15 10:45 nagiosCFG.DEBUG
-rw-r--r-- 1 apache centreon 1121 Oct 15 10:45 resource.cfg
-rw-r--r-- 1 apache centreon 2720 Oct 15 10:45 servicegroups.cfg
-rw-r--r-- 1 apache centreon 12341 Oct 15 10:45 services.cfg
-rw-r--r-- 1 apache centreon 12030 Oct 15 10:45 serviceTemplates.cfg
-rw-r--r-- 1 apache centreon 2701 Oct 15 10:45 timeperiods.cfg

filesGeneration/nagiosCFG/4:
total 1856
-rw-r--r-- 1 apache centreon 3898 Oct 15 10:45 centengine.cfg
-rw-r--r-- 1 apache centreon 9155 Oct 15 10:45 commands.cfg
-rw-r--r-- 1 apache centreon 1662 Oct 15 10:45 connectors.cfg
-rw-r--r-- 1 apache centreon 16483 Oct 15 10:45 contacts.cfg
-rw-r--r-- 1 apache centreon 92188 Oct 15 10:45 hostgroups.cfg
-rw-r--r-- 1 apache centreon 497258 Oct 15 10:45 hosts.cfg
-rw-r--r-- 1 apache centreon 6782 Oct 15 10:45 hostTemplates.cfg
-rw-r--r-- 1 apache centreon 4402 Oct 15 10:45 nagiosCFG.DEBUG
-rw-r--r-- 1 apache centreon 1121 Oct 15 10:45 resource.cfg
-rw-r--r-- 1 apache centreon 21519 Oct 15 10:45 servicegroups.cfg
-rw-r--r-- 1 apache centreon 1159291 Oct 15 10:45 services.cfg
-rw-r--r-- 1 apache centreon 22413 Oct 15 10:45 serviceTemplates.cfg
-rw-r--r-- 1 apache centreon 3743 Oct 15 10:45 timeperiods.cfg
-rw-r--r-- 1 apache centreon 2620 Oct 15 10:45 contactgroups.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 dependencies.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 escalations.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_commands.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_host.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_services.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_timeperiod.cfg

filesGeneration/nagiosCFG/1:
total 1152
-rw-r--r-- 1 apache centreon 3899 Oct 15 10:45 centengine.cfg
-rw-r--r-- 1 apache centreon 34028 Oct 15 10:45 commands.cfg
-rw-r--r-- 1 apache centreon 1662 Oct 15 10:45 connectors.cfg
-rw-r--r-- 1 apache centreon 30396 Oct 15 10:45 contacts.cfg
-rw-r--r-- 1 apache centreon 22555 Oct 15 10:45 hostgroups.cfg
-rw-r--r-- 1 apache centreon 179755 Oct 15 10:45 hosts.cfg
-rw-r--r-- 1 apache centreon 18039 Oct 15 10:45 hostTemplates.cfg
-rw-r--r-- 1 apache centreon 4403 Oct 15 10:45 nagiosCFG.DEBUG
-rw-r--r-- 1 apache centreon 1121 Oct 15 10:45 resource.cfg
-rw-r--r-- 1 apache centreon 63035 Oct 15 10:45 servicegroups.cfg
-rw-r--r-- 1 apache centreon 674250 Oct 15 10:45 services.cfg
-rw-r--r-- 1 apache centreon 67256 Oct 15 10:45 serviceTemplates.cfg
-rw-r--r-- 1 apache centreon 17889 Oct 15 10:45 timeperiods.cfg
-rw-r--r-- 1 apache centreon 5263 Oct 15 10:45 contactgroups.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 dependencies.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 escalations.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_commands.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_host.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_services.cfg
-rw-r--r-- 1 apache centreon 1088 Oct 15 10:45 meta_timeperiod.cfg

filesGeneration/broker/6:
total 4
-rw-r--r-- 1 apache centreon 2025 Oct 15 10:45 poller-module.xml

filesGeneration/broker/4:
total 4
-rw-r--r-- 1 apache centreon 2025 Oct 15 10:45 poller-module.xml

filesGeneration/broker/1:
total 16
-rw-r--r-- 1 apache centreon 4897 Oct 15 10:45 central-broker.xml
-rw-r--r-- 1 apache centreon 1965 Oct 15 10:45 central-module.xml
-rw-r--r-- 1 apache centreon 2398 Oct 15 10:45 central-rrd.xml

/etc/centreon-broker:
total 60
-rw-rw-r-- 1 centreon-broker centreon-broker 4897 Oct 15 10:45 central-broker.xml
-rw-rw-r-- 1 centreon-broker centreon-broker 1965 Oct 15 10:45 central-module.xml
-rw-rw-r-- 1 centreon-broker centreon-broker 2398 Oct 15 10:45 central-rrd.xml`

depuis je me retrouve sans graphs voir ci-dessous svp (désolé pour la qualité...)
![capture](https://cloud.githubusercontent.com/assets/23102533/19773233/1909b4f4-9c69-11e6-84ba-4711e83b232a.PNG)

Voici les éléments que j'ai récolté :

je me retrouve avec 22310 fichiers rrd dans "metrics" et 13114 fichiers rrd dans "status" alors que je n'ai que 6560 services ;
142 205 402 enregistrements dans ma table data_bin avec un "id_metric" qui va de 4366 à 100293;

~ 12,574 enregistrements dans ma table metrics avec un "metric_id" qui va de 86399 à 100293 et un "index_id" qui va de 100293 à 6040934

6 563 enregistrements dans ma table index_data avec un "id" qui va de 5795102 à 6040934.

rrdtool.log :
les graphs sont bien crées... `RDDTOOL: graph - --width=550 --height=140 --title=' Citrix_CPU graph on S6I351 ' --start=1477318888 --end=1477491688 --interlaced --imgformat=PNG --vertical-label=' Processor Use ' --slope-mode --base=1000 --lower-limit=0 --upper-limit=110 --rigid --alt-autoscale-max --color BACK#FFFFFF --color FRAME#FFFFFF --color SHADEA#EFEFEF --color SHADEB#EFEFEF --color ARROW#FF0000 COMMENT:" From 2016/10/24 16\:21 to 2016/10/26 16\:21 \c` 

central-rrd-master.log :
`[1477493218] [0x7fec30002a30] debug: BBDO: got new header with a size of 41 and an ID of 131073
[1477493218] [0x7fec30002a30] debug: BBDO: got new header with a size of 27 and an ID of 131076
[1477493218] [0x7fec30002a30] debug: BBDO: got new header with a size of 47 and an ID of 131073
[1477493222] [0x11e6a00] debug: RRD: updating file '/var/lib/centreon/metrics/81108.rrd' (1476799328:2.000000)
[1477493222] [0x11e6a00] error: RRD: failed to update value in file '/var/lib/centreon/metrics/81108.rrd': '/var/lib/centreon/metrics/81108.rrd' is too small (should be 150568 bytes)`

central-module-master.log :
`[1477412782] [0x3166220] debug: multiplexing: starting
[1477412794] [0x33789c0] debug: BBDO: got new header with a size of 22 and an ID of 4294901761
[1477412795] [0x33789c0] debug: BBDO: got new header with a size of 90 and an ID of 65553
[1477412795] [0x33789c0] debug: BBDO: got new header with a size of 99 and an ID of 65553`

si quelqu'un saurait me filer un coup de main ce serait super, parce que là je bloque et je ne vois pas où, je me tate à redémarrer centreon entièrement mais je préfère voir si quelqu'un aurait une soluce ou ne serait-ce que des pistes, sachant que mon FS /var/lib/centreon est full...
Merci de m'avoir lu en tout cas 

PS : les BDD c'est vraiment pas mon dada.

**Comment by Sims24** [comment]
Hello, @nikitito 

Tu dois avoir toucher à la durée de rétention de tes RRDs à un moment donné dans Administration > Options > Centstorage.

Fait un 'grep rrd_length /etc/centreon-broker/*' et compare la valeur avec la taille d'un RRD sur ton disque. 

C'est normal que tu aies plus de fichiers dans /var/lib/centreon/metrics que ton nombre de service du fait des suppressions et surtout parce que un service ping possède une graph avec 4 courbes donc 4 RRDs !

Cherches par là,

++

**Comment by nikitito** [comment]
Salut Sims24,
je te remercie pour ta réactivité.
Je n'ai pas touché à la durée de rétention, elle est toujours à 180 jours pour les bases RRD.
Et rien avec le mot length dans /etc/centreon-broker/.
Je me demandais est-ce que je peux vider les dossiers 'metrics' et 'status' et recharger la conf pour tout recréer ?
D'avance merci à toi.

**Comment by nikitito** [comment]
Hello,
need help please, j'ai redémarrer les collecteurs, le FS n'est plus Full et je ne vois vraiment pas ce qui bloque !

**Comment by nikitito** [comment]
Quand je fais un POLLERTEST, voici ce qu'il me retourne : 
"ERROR: Unknown poller...
13      Central
14      Poller1
15      Poller3"

**Comment by nikitito** [comment]
Dans la configuration de CB pour central-module-master, je n'ai pas d'input, est-ce que ce peut-être l'origine de mon problème ?

**Comment by nikitito** [comment]
Voici une partie des stats du broker, comment est-ce possible que certaines dates de dernières connexion ou dernier évènement soient au 26/10 ?

CENTRAL-BROKER-MASTER

central-broker-master-input - Entrée[ + ]
Statut                                  listening
Dernier évènement à                     0
Vitesse de traitement des évènements    0.0 events/s
one peer retention mode                 false
Dernier essai de connxion               2016-11-02 08:17:48
Dernière connexion réalisée             0

centreon-broker-master-rrd - Statut détaillé[ + ]
Statut                                 connecting
Vitesse de traitement des évènements   6.1 events/s
Dernier essai de connxion              2016-10-26 18:34:53
Dernière connexion réalisée            2016-10-26 18:34:53
Dernier évènement à                    2016-11-02 08:17:47
File d'évènements                      0
Activation du fichier temporaire       no
Type d'évènements accepté              storage

central-broker-master-sql - Statut détaillé[ + ]
Statut                                 connecting
Vitesse de traitement des évènements   7.3 events/s
Dernier essai de connxion              2016-10-26 18:34:53
Dernière connexion réalisée            2016-10-26 18:34:53
Dernier évènement à                    2016-11-02 08:17:48
File d'évènements                      0
Activation du fichier temporaire       no
Type d'évènements accepté              neb
                                       correlation

central-broker-master-perfdata - Statut détaillé[ + ]
Statut                                 connecting
Vitesse de traitement des évènements   7.3 events/s
Dernier essai de connxion              2016-10-26 18:34:53
Dernière connexion réalisée            2016-10-26 18:34:53
Dernier évènement à                    2016-11-02 08:17:48
File d'évènements                      0
Activation du fichier temporaire       no
Type d'évènements accepté              neb


CENTRAL-RRD-MASTER

central-rrd-master-input - Entrée[ + ]
Statut                                 listening
Dernier évènement à                    0
Vitesse de traitement des évènements   0.0 events/s
one peer retention mode                false
Dernier essai de connxion              2016-11-02 08:17:48
Dernière connexion réalisée            0

central-rrd-master-output - Statut détaillé[ + ]
Statut                                 connected
Vitesse de traitement des évènements   0.0 events/s
                                       file_expected_terminated_at 1478071068
Taille maximale du fichier             524288000
file_percent_processed                 0.0971794%
Indice de lecture du fichier           679944
Chemin du fichier en cours de lecture  /var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention
                                       Indice d'écriture du fichier           175390866
Chemin du fichier en cours d'écriture  /var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention1
                                       Dernier essai de connxion 2016-11-02 08:17:31
Dernière connexion réalisée            2016-11-02 08:17:31
Dernier évènement à                    2016-10-26 18:34:53
File d'évènements                      0
Activation du fichier temporaire       no
Failover                               central-rrd-master-output-output-failover
Type d'évènements accepté              all

central-rrd-master-output-output-failover - Statut détaillé[ + ]
Statut                                 connected
Taille maximale du fichier             524288000
file_percent_processed                 0.0971794%
Indice de lecture du fichier           679944
Chemin du fichier en cours de lecture  /var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention
                                       Indice d'écriture du fichier 175390866
Chemin du fichier en cours d'écriture  /var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention1
                                       File d'évènements 0
Activation du fichier temporaire       no
Dernier évènement à                    2016-11-02 08:17:47
Vitesse de traitement des évènements   6.1 events/s
                                       Dernier essai de connxion 2016-10-26 18:34:53
Dernière connexion réalisée            2016-10-26 18:34:53
Type d'évènements accepté              all


Si quelqu'un à une piste, merci d'avoir jeter un coup d'oeil.

**Comment by Sims24** [comment]
Hello, 

Peux tu poster ta configuration centrale broker en pièce-jointe : 

/etc/centreon-broker/central-broker.xml
/etc/centreon-broker/central-rrd.xml

et également un fichier d'un poller, e.g central-module.xml. 

Ça serait bien d'avoir également les fichiers de logs.

**Comment by nikitito** [comment]
Bonjour,
que voici 
[central-broker.xml.txt](https://github.com/centreon/centreon-broker/files/565957/central-broker.xml.txt)
[central-module.xml.txt](https://github.com/centreon/centreon-broker/files/565955/central-module.xml.txt)
[central-rrd.xml.txt](https://github.com/centreon/centreon-broker/files/565956/central-rrd.xml.txt)

Egalement un petit bout de log.
[central-broker-master.log.txt](https://github.com/centreon/centreon-broker/files/565960/central-broker-master.log.txt)

Merci à toi

**Comment by Sims24** [comment]
Hi @nikitito 

Please post also central-rrd log file and result of following commands : 

ps aux | grep broker
netstat -plantu | grep cbd 

Thanks,

**Comment by nikitito** [comment]
there it is
ps aux | grep broker : 
 /usr/sbin/cbd /etc/centreon-broker/central-rrd.xml
/usr/sbin/cbd /etc/centreon-broker/central-broker.xml

netstat -plantu | grep cbd : 
tcp        0      0 0.0.0.0:5669                0.0.0.0:*                   LISTEN      30359/cbd
tcp        0      0 0.0.0.0:5670                0.0.0.0:*                   LISTEN      30320/cbd
tcp        0      0 central:5669             poller1:57032           ESTABLISHED 30359/cbd
tcp        0      0 127.0.0.1:5669              127.0.0.1:48028             ESTABLISHED 30359/cbd
tcp        0      0 central:5669             poller2:41932           ESTABLISHED 30359/cbd
tcp        0      0 127.0.0.1:33384             127.0.0.1:5670              ESTABLISHED 30359/cbd
tcp        0      0 127.0.0.1:5670              127.0.0.1:33384             ESTABLISHED 30320/cbd

[central-rrd-master.log.txt](https://github.com/centreon/centreon-broker/files/566477/central-rrd-master.log.txt)

**Comment by Sims24** [comment]
Hi @nikitito ,

This is a corrupted RRD file, did you copy RRD from a 32bits to a 64 bits arch ? 

Please move the rrd that is causing the problem and restart broker : 

mv /var/lib/centreon/metrics/81138.rrd /tmp/81138.rrd.bckp 
/etc/init.d/cbd restart

Wait 5 minutes and send us the content of the stats files.

**Comment by nikitito** [comment]
content of central-rrd-master.stats.txt


broker
version=2.11.2
pid=4690
now=1478091790
compiled with qt=4.7.4
running with qt=4.7.4

module /usr/share/centreon/lib/centreon-broker/50-tcp.so
state=loaded
size=78960B

module /usr/share/centreon/lib/centreon-broker/20-correlation.so
state=loaded
size=140552B

module /usr/share/centreon/lib/centreon-broker/80-bbdo.so
state=loaded
size=605400B

module /usr/share/centreon/lib/centreon-broker/05-dumper.so
state=loaded
size=267032B

module /usr/share/centreon/lib/centreon-broker/10-neb.so
state=loaded
size=94880B

module /usr/share/centreon/lib/centreon-broker/15-stats.so
state=loaded
size=70400B

module /usr/share/centreon/lib/centreon-broker/60-compression.so
state=loaded
size=45600B

module /usr/share/centreon/lib/centreon-broker/20-storage.so
state=loaded
size=161784B

module /usr/share/centreon/lib/centreon-broker/80-sql.so
state=loaded
size=486776B

module /usr/share/centreon/lib/centreon-broker/70-rrd.so
state=loaded
size=116360B

module /usr/share/centreon/lib/centreon-broker/20-bam.so
state=loaded
size=848200B

module /usr/share/centreon/lib/centreon-broker/80-ndo.so
state=loaded
size=484408B

module /usr/share/centreon/lib/centreon-broker/50-file.so
state=loaded
size=61808B

module /usr/share/centreon/lib/centreon-broker/60-tls.so
state=loaded
size=70984B

input central-rrd-master-input
state=listening
last event at=0
event processing speed=0.0 events/s
one peer retention mode=false
peers=1
  127.0.0.1:59582
last connection attempt=1478091789
last connection success=0

output central-rrd-master-output
state=disconnected (RRD: failed to update value in file '/var/lib/centreon/metrics/77090.rrd': '/var/lib/centreon/metrics/77090.rrd' is too small (should be 150568 bytes))
accepted events
  all
event processing speed=3.3events/s
file_expected_terminated_at=1478091790
file_max_size=524288000
file_percent_processed=0.178147%
file_read_offset=1277960
file_read_path=/var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention
file_write_offset=193074241
file_write_path=/var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention1
last connection attempt=1478091075
last connection success=1478091075
last event at=1478091787
queued events=0
state=connected
temporary recovery mode=no
last event at=1478091174
event processing speed=0.0 events/s
last connection attempt=1478091775
last connection success=1478091775
failover
  output central-rrd-master-output-output-failover
  state=connected
  file_max_size=524288000
  file_percent_processed=0.178147%
  file_read_offset=1277960
  file_read_path=/var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention
  file_write_offset=193074241
  file_write_path=/var/lib/centreon-broker/central-rrd-master_central-rrd-master-output.retention1
  accepted events
    all
  queued events=0
  temporary recovery mode=no
  last event at=1478091787
  event processing speed=3.3 events/s
  last connection attempt=1478091075
  last connection success=1478091075


Thank you for your time, because i'm really lost with the broker.

**Comment by Sims24** [comment]
Ok, looks like several rrd are broken. 

Cf last question, did you copy rrd from a 32bits arch to a 64bits arch ? 

Only thing to do is to move all corrupted rrd like /var/lib/centreon/metrics/77090.rrd here, and restart the broker. 

mv /var/lib/centreon/metrics/77090.rrd /tmp/77090.rrd.bck 
service cbd restart

do this until now error show up in central-rrd log/stats file. 

Regards

**Comment by nikitito** [comment]
I just did it for 77090.rrd 3minutes ago and restard cbd.
What do you mean by "did you copy rrd from a 32bits arch to a 64bits arch ?", cause I didn't copy nothing ... ?

**Comment by nikitito** [comment]
my server is a x64

**Comment by nikitito** [comment]
Do you mean that I need to empty my metrics folder and restart cbd ?

**Comment by Sims24** [comment]
Trying to figure out why you have some corrupted rrd files :) It's prelly unusual ... !

But if you have this errors for all your rrds, you will need to empty this directory and rebuild from databases through "Administration > Perf management .." menu. 

This is a long and painful process, you cannot rebuild all at once, I recommend to do this step by step (10 graphs every 2 hours ...). 

Good luck if you take this way it will take some time :)

**Comment by nikitito** [comment]
Thanks to you ;)
