### ISSUE TITLE
Custom step/heartbeat for rrd

### ISSUE THREAD

**Issue by Iralein** [centreon/centreon-broker#70]
Hi,

We do have some metrics which are updated only one a day. The default step and heartbeat are not suitable for such metrics. (-> empty graphs in Centreon GUI)
It would be nice if one can change the step/heartbeat values for rrd creation.
Regards,

Ira

**Comment by ganoze** [comment]
Empty graphs should not happen if your services are properly configured with a 24 hours check interval. In that case the step would be of 24 hours and the heartbeat of 10 times that duration. Can you confirm that your services have a 24 hours check interval ?

On step/heartbeat or more globally on RRD files customization however, there is no current development  planned to implement this feature. However I explained in PR #104 what it would take for this feature to be included, should PR be proposed.
