### ISSUE TITLE
Enregistrement non supprimé dans centreon_storage.services_servicegroups

### ISSUE THREAD

**Issue by nikitito** [centreon/centreon-broker#71]
Bonjour,
en espérant que cela parle à quelqu'un ;)
J'ai remarqué que les enregistrements dans services_servicegroups ne sont pas supprimés ( même après modification ), ce qui est assez embêtant car ces informations sont remontés en direct sur un site et l'information est donc fausse.
Je m'explique, j'ai affecté un SG_A au lieu de SG_B à un service, j'ai donc rectifié le tir et supprimé SG_A rajouter SG_B à la place au niveau des relations du service en question.
Seul problème c'est que l'enregistrement est toujours présent dans la base et je le supprime donc à la mano, ce n'est pas la première fois ...
Quelqu'un aurait-il une idée ?
Merci de m'avoir lu.

Cordialement,
Nikitito

**Comment by julienmathis** [comment]
Bonjour, 

As tu appliqué le modification et redémarré Engine ?

**Comment by nikitito** [comment]
Oui

**Comment by nikitito** [comment]
Merci de prendre du temps pour me répondre ;)

**Comment by julienmathis** [comment]
Quelle version de Centreon Web et Broker ?

--
Julien  MATHIS

Co-Founder & Chief Technical Officer

Standard: +33 (0) 1 49 69 97 12
Direct: +33(0)1 82 21 80 12
jmathis@centreon.com <jmathis@merethis.com>
[image: Centreon_Logo_RVB_Light_200x76px.png]
*The Power Of Knowing*
Website <http://www.centreon.com/> | Blog <http://blog.centreon.com/>
| Github <https://github.com/centreon/> | Twitter
<https://twitter.com/Centreon>

**Comment by nikitito** [comment]
2.7.5 pour Web et 2.11.2 pour le broker
Pas bougé depuis fin juillet et j'ai remarqué ça samedi, aucunes modifications avec de possibles conséquences n'a été faite

**Comment by nikitito** [comment]
Cela ne parle à personne donc ?

**Comment by nikitito** [comment]
Bon les suppressions des anciennes instances ne sont pas faites non plus ...
quels droits doivent être appliqués sur /usr/share/centreon/filesGeneration/broker/ et /usr/share/centreon/filesGeneration/nagiosCFG/ svp ?

**Comment by julienmathis** [comment]
Peut on avoir la structure de la table : 
desc services_servicegroups;

**Comment by nikitito** [comment]
Que voulez-vous dire par la structure ?
j'ai trois champs ( host_id ; service_id ; servicegroup_id )
Je suis désolé mais les bases c'est pas mon fort...

**Comment by julienmathis** [comment]
Connecte toi au mysql : 

mysql -u USER -p centreon_storage

Et lance la commande : 

desc services_servicegroups;

si tu peux nous donner le résultat :)

**Comment by nikitito** [comment]
voilà le résultat : 
 Field                    | Type     | Null   | Key   | Default | Extra |
+-----------------+---------+------+-----+---------+-------+
| host_id               | int(11)   | NO    | PRI   | NULL    |       |
| service_id           | int(11)   | NO    | PRI   | NULL    |       |
| servicegroup_id | int(11)   | NO    | PRI   | NULL    |       |
+-----------------+---------+------+-----+---------+-------+

**Comment by julienmathis** [comment]
Je ne vois pas le problème. Je laisse @ganoze voir avec toi.

**Comment by nikitito** [comment]
Ok merci d'avoir jeter un coup d'oeil ;)
Bonne journée

**Comment by nikitito** [comment]
Bonjour,
toujours pas de news de votre côté ?
Pour l'instant pas d'erreur, mais je n'ai pas affecté un mauvais SG depuis ...

**Comment by nikitito** [comment]
Bonjour ?
ce problème n'est toujours pas résolu, Voici les enregistrements en BDD (table services_servicegroups)
host_id	service_id	servicegroup_id
5284	        52259	106                           PAS BON !! :@
5284 	52259      107                           Bon :-)

Pourquoi le premier enregistrement ne se supprime pas quand on recharge la conf alors qu'il est supprimé au niveau de la relation du service ?
Merci à ceux qui peuvent me donner une piste, je bloque ...

**Comment by nikitito** [comment]
Bonjour,
Le problème est présent sur d'autres tables et je ne suis pas le seul à avoir rencontré cette problématique.

https://forum.centreon.com/forum/centreon-ui/centreon-web-interface/140374-centreon-2-7-0-suppression-de-poller

**Comment by ganoze** [comment]
Salut, il semble que ce problème a été corrigé dans les dernières versions de Centreon Engine (1.5.3) et de Centreon Broker (2.11.8). J'ai vérifié que la suppression était bien effective dans la table services_servicegroups avec ces versions.

N'hésite pas à réouvrir ce ticket si ce n'est pas le cas.
