### ISSUE TITLE
CBD sur les serveurs satellites

### ISSUE THREAD

**Issue by nikitito** [centreon/centreon-broker#73]
Bonjour,
j'ai hérité d'une plateforme il y a quelques mois et tout fonctionne très bien (excepter un problème d'écriture en bdd mais c'est une autre histoire)...
Juste 2 questions : est-ce que cbd doit être activé sur les pollers et s'il ne l'est pas quelles en sont les conséquences ?
Je viens de remarquer que CBD n'est pas en cours d'exécution sur mes pollers mais juste sur le central.
D'avance merci à ceux qui peuvent éclairer ma lanterne

Bonne journée

**Comment by BenoitPoulet** [comment]
Bonjour,

Ici c'est un bug tracker, pour de l'aide vous aurez plus de succès ici : https://forum.centreon.com/
