### ISSUE TITLE
mySQL Insert

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon-broker#82]
Hello,

after a reboot of my system, the mysql database is broken. That is a known issue with the old myISAM schema, and yes, i will merge it soon to innoDB, but the interesting problem i want to report:

```
[1483914748] [0x212f4a0] error:   storage: could not insert data in log_data_bin: could not execute query: Incorrec
t key file for table './centreon_storage/data_bin.MYI'; try to repair it QMYSQL: Unable to execute query (INSERT IN
TO data_bin  (id_metric   , ctime, status, value)  VALUES (1469, 1483902837, 0, '0.0000000000e+00'), (1470, 1483902
837, 0, 9.9160000000e+01), (1471, 1483902837, 0, 1.0000000000e-02), (1472, 1483902837, 0, 3.8000000000e-01), (1473,
 1483902837, 0, 3.1000000000e-01), (1474, 1483902837, 0, 7.0000000000e-02), (147
```

The Broker is running, and detected, that the mySQL database has a problem and did not accept the insert request, but the broker did not store the unsuccessful data.

I think it whould be a great, if something (whatever) goes wrong with the database, and yes, i know, if the connect is unsuccessful the data got stored, but i whould reccomend, that this function is also applied on the insert level.

**Comment by ganoze** [comment]
Hi,

Thank you for your feedback, it is very much appreciated. Indeed two tables were handled very differently than the standard query system (with data acknowledgement) for performance purposes. These were _logs_ and _data_bin_. As you perfectly noticed, the downside of these performance was that data could get lost in case of database failure.

Starting with the upcoming version 3.1 of Centreon Broker, _logs_ and _data_bin_ will be queries like other tables and therefore data will be acknowledged and replayed in case of failure. This finishes the work started globally on Centreon products to move these two tables from MyISAM to InnoDB.
