### ISSUE TITLE
Retention files do not process event acknowledgement

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon-broker#84]
Centreon Broker retention files (memory file, queue files, other files) do not process event acknowledgement properly. In some cases this might lead to some limited event loss but which can trigger other downstream issues such as non-existing database entries (see centreon/centreon#4966). The most common of these cases is a Centreon restart/reload with host or service creation.

It is necessary to rework the event acknowledgement system in order to keep events in file as long as they've not been acknowledged.

**Comment by romnvll** [comment]
Est-ce qu'il y a une solution de contournement?
Merci, bonne soirée.

**Comment by ganoze** [comment]
Unfortunately, not yet.
