### ISSUE TITLE
cbd: undefined symbol: _ZN16QCoreApplicationC1ERiPPci

### ISSUE THREAD

**Issue by ludovic-lage** [centreon/centreon-broker#86]
Hello, 

I'm trying to install centreon-broker-3.0.3.4-el7 on Centos 7.
I'm not using Nagios.

But when I try to launch cbd or cbwd, I have this error : 

[root@centreon-v7 ~]# cbd
cbd: symbol lookup error: cbd: undefined symbol: _ZN16QCoreApplicationC1ERiPPci

With strace : 

execve("/sbin/cbwd", ["/sbin/cbwd"], [/* 22 vars */]) = 0
brk(0)                                  = 0x20ff000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a50000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=34471, ...}) = 0
mmap(NULL, 34471, PROT_READ, MAP_PRIVATE, 4, 0) = 0x7f36e4a47000
close(4)                                = 0
open("/lib64/libQtXml.so.4", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\3\1\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=272304, ...}) = 0
mmap(NULL, 2367400, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e45f0000
mprotect(0x7f36e4630000, 2097152, PROT_NONE) = 0
mmap(0x7f36e4830000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x40000) = 0x7f36e4830000
close(4)                                = 0
open("/lib64/libQtSql.so.4", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200\367\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=247112, ...}) = 0
mmap(NULL, 2342568, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e43b4000
mprotect(0x7f36e43ef000, 2093056, PROT_NONE) = 0
mmap(0x7f36e45ee000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x3a000) = 0x7f36e45ee000
close(4)                                = 0
open("/lib64/libQtNetwork.so.4", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\22\3\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=1212616, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a46000
mmap(NULL, 3308368, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e408c000
mprotect(0x7f36e41ae000, 2093056, PROT_NONE) = 0
mmap(0x7f36e43ad000, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x121000) = 0x7f36e43ad000
close(4)                                = 0
open("/lib64/libQtCore.so.4", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\277\6\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=2639240, ...}) = 0
mmap(NULL, 4736992, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e3c07000
mprotect(0x7f36e3e80000, 2097152, PROT_NONE) = 0
mmap(0x7f36e4080000, 45056, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x279000) = 0x7f36e4080000
mmap(0x7f36e408b000, 2016, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e408b000
close(4)                                = 0
open("/lib64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\265\5\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=999944, ...}) = 0
mmap(NULL, 3179552, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e38fe000
mprotect(0x7f36e39e7000, 2097152, PROT_NONE) = 0
mmap(0x7f36e3be7000, 45056, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0xe9000) = 0x7f36e3be7000
mmap(0x7f36e3bf2000, 82976, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e3bf2000
close(4)                                = 0
open("/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`T\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=1141928, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a45000
mmap(NULL, 3150152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e35fc000
mprotect(0x7f36e36fc000, 2097152, PROT_NONE) = 0
mmap(0x7f36e38fc000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x100000) = 0x7f36e38fc000
close(4)                                = 0
open("/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360*\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=88720, ...}) = 0
mmap(NULL, 2184192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e33e6000
mprotect(0x7f36e33fb000, 2093056, PROT_NONE) = 0
mmap(0x7f36e35fa000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x14000) = 0x7f36e35fa000
close(4)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\34\2\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=2118128, ...}) = 0
mmap(NULL, 3932672, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e3025000
mprotect(0x7f36e31db000, 2097152, PROT_NONE) = 0
mmap(0x7f36e33db000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x1b6000) = 0x7f36e33db000
mmap(0x7f36e33e1000, 16896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e33e1000
close(4)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240l\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=143944, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a44000
mmap(NULL, 2208864, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e2e09000
mprotect(0x7f36e2e20000, 2093056, PROT_NONE) = 0
mmap(0x7f36e301f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x16000) = 0x7f36e301f000
mmap(0x7f36e3021000, 13408, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e3021000
close(4)                                = 0
open("/lib64/libz.so.1", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p!\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=90664, ...}) = 0
mmap(NULL, 2183688, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e2bf3000
mprotect(0x7f36e2c08000, 2093056, PROT_NONE) = 0
mmap(0x7f36e2e07000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x14000) = 0x7f36e2e07000
close(4)                                = 0
open("/lib64/libssl.so.10", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\205\1\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=454024, ...}) = 0
mmap(NULL, 2544944, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e2985000
mprotect(0x7f36e29e9000, 2093056, PROT_NONE) = 0
mmap(0x7f36e2be8000, 45056, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x63000) = 0x7f36e2be8000
close(4)                                = 0
open("/lib64/libcrypto.so.10", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\204\6\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=2025472, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a43000
mmap(NULL, 4104152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e259b000
mprotect(0x7f36e275b000, 2097152, PROT_NONE) = 0
mmap(0x7f36e295b000, 155648, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x1c0000) = 0x7f36e295b000
mmap(0x7f36e2981000, 16344, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e2981000
close(4)                                = 0
open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\16\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=19776, ...}) = 0
mmap(NULL, 2109744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e2397000
mprotect(0x7f36e2399000, 2097152, PROT_NONE) = 0
mmap(0x7f36e2599000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x2000) = 0x7f36e2599000
close(4)                                = 0
open("/lib64/libgthread-2.0.so.0", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\6\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=6944, ...}) = 0
mmap(NULL, 2101312, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e2195000
mprotect(0x7f36e2196000, 2093056, PROT_NONE) = 0
mmap(0x7f36e2395000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0) = 0x7f36e2395000
close(4)                                = 0
open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\"\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=44448, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a42000
mmap(NULL, 2128952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e1f8d000
mprotect(0x7f36e1f94000, 2093056, PROT_NONE) = 0
mmap(0x7f36e2193000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x6000) = 0x7f36e2193000
close(4)                                = 0
open("/lib64/libglib-2.0.so.0", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\250\1\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=1287896, ...}) = 0
mmap(NULL, 3368336, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e1c56000
mprotect(0x7f36e1d8a000, 2097152, PROT_NONE) = 0
mmap(0x7f36e1f8a000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x134000) = 0x7f36e1f8a000
mmap(0x7f36e1f8c000, 1424, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e1f8c000
close(4)                                = 0
open("/lib64/libgssapi_krb5.so.2", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\306\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=324888, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a41000
mmap(NULL, 2414784, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e1a08000
mprotect(0x7f36e1a53000, 2097152, PROT_NONE) = 0
mmap(0x7f36e1c53000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x4b000) = 0x7f36e1c53000
close(4)                                = 0
open("/lib64/libkrb5.so.3", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240U\2\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=959008, ...}) = 0
mmap(NULL, 3041536, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e1721000
mprotect(0x7f36e17f7000, 2097152, PROT_NONE) = 0
mmap(0x7f36e19f7000, 69632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0xd6000) = 0x7f36e19f7000
close(4)                                = 0
open("/lib64/libcom_err.so.2", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\25\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=15848, ...}) = 0
mmap(NULL, 2109928, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e151d000
mprotect(0x7f36e1520000, 2093056, PROT_NONE) = 0
mmap(0x7f36e171f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x2000) = 0x7f36e171f000
close(4)                                = 0
open("/lib64/libk5crypto.so.3", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0pF\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=202568, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a40000
mmap(NULL, 2298328, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e12eb000
mprotect(0x7f36e131a000, 2093056, PROT_NONE) = 0
mmap(0x7f36e1519000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x2e000) = 0x7f36e1519000
mmap(0x7f36e151c000, 472, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e151c000
close(4)                                = 0
open("/lib64/libkrb5support.so.0", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\3406\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=62744, ...}) = 0
mmap(NULL, 2156136, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e10dc000
mprotect(0x7f36e10e9000, 2097152, PROT_NONE) = 0
mmap(0x7f36e12e9000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0xd000) = 0x7f36e12e9000
close(4)                                = 0
open("/lib64/libkeyutils.so.1", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\25\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=15688, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a3f000
mmap(NULL, 2109720, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e0ed8000
mprotect(0x7f36e0edb000, 2093056, PROT_NONE) = 0
mmap(0x7f36e10da000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x2000) = 0x7f36e10da000
close(4)                                = 0
open("/lib64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\3209\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=111080, ...}) = 0
mmap(NULL, 2202264, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e0cbe000
mprotect(0x7f36e0cd4000, 2097152, PROT_NONE) = 0
mmap(0x7f36e0ed4000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x16000) = 0x7f36e0ed4000
mmap(0x7f36e0ed6000, 6808, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e0ed6000
close(4)                                = 0
open("/lib64/libselinux.so.1", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300j\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=155744, ...}) = 0
mmap(NULL, 2255216, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e0a97000
mprotect(0x7f36e0abb000, 2093056, PROT_NONE) = 0
mmap(0x7f36e0cba000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x23000) = 0x7f36e0cba000
mmap(0x7f36e0cbc000, 6512, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f36e0cbc000
close(4)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a3e000
open("/lib64/libpcre.so.1", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\25\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=398264, ...}) = 0
mmap(NULL, 2490888, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f36e0836000
mprotect(0x7f36e0896000, 2093056, PROT_NONE) = 0
mmap(0x7f36e0a95000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x5f000) = 0x7f36e0a95000
close(4)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a3d000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a3c000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a3b000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a39000
arch_prctl(ARCH_SET_FS, 0x7f36e4a39840) = 0
mprotect(0x7f36e33db000, 16384, PROT_READ) = 0
mprotect(0x7f36e301f000, 4096, PROT_READ) = 0
mprotect(0x7f36e0a95000, 4096, PROT_READ) = 0
mprotect(0x7f36e2599000, 4096, PROT_READ) = 0
mprotect(0x7f36e0cba000, 4096, PROT_READ) = 0
mprotect(0x7f36e0ed4000, 4096, PROT_READ) = 0
mprotect(0x7f36e10da000, 4096, PROT_READ) = 0
mprotect(0x7f36e12e9000, 4096, PROT_READ) = 0
mprotect(0x7f36e1519000, 8192, PROT_READ) = 0
mprotect(0x7f36e171f000, 4096, PROT_READ) = 0
mprotect(0x7f36e19f7000, 57344, PROT_READ) = 0
mprotect(0x7f36e1c53000, 4096, PROT_READ) = 0
mprotect(0x7f36e1f8a000, 4096, PROT_READ) = 0
mprotect(0x7f36e2193000, 4096, PROT_READ) = 0
mprotect(0x7f36e2395000, 4096, PROT_READ) = 0
mprotect(0x7f36e2e07000, 4096, PROT_READ) = 0
mprotect(0x7f36e295b000, 106496, PROT_READ) = 0
mprotect(0x7f36e2be8000, 16384, PROT_READ) = 0
mprotect(0x7f36e35fa000, 4096, PROT_READ) = 0
mprotect(0x7f36e38fc000, 4096, PROT_READ) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a38000
mprotect(0x7f36e3be7000, 36864, PROT_READ) = 0
mprotect(0x615000, 4096, PROT_READ)     = 0
mprotect(0x7f36e4a51000, 4096, PROT_READ) = 0
munmap(0x7f36e4a47000, 34471)           = 0
set_tid_address(0x7f36e4a39b10)         = 3736
set_robust_list(0x7f36e4a39b20, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f36e2e0f780, [], SA_RESTORER|SA_SIGINFO, 0x7f36e2e18370}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f36e2e0f810, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f36e2e18370}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
statfs("/sys/fs/selinux", 0x7fff00e53260) = -1 ENOENT (No such file or directory)
statfs("/selinux", {f_type="EXT2_SUPER_MAGIC", f_bsize=4096, f_blocks=2031470, f_bfree=956293, f_bavail=847340, f_files=524288, f_ffree=475605, f_fsid={620051, -2059781616}, f_namelen=255, f_frsize=4096}) = 0
brk(0)                                  = 0x20ff000
brk(0x2120000)                          = 0x2120000
open("/proc/filesystems", O_RDONLY)     = 4
fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36e4a4f000
read(4, "nodev\tsysfs\nnodev\trootfs\nnodev\tr"..., 1024) = 411
stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7fff00e53140) = -1 ENOENT (No such file or directory)
read(4, "", 1024)                       = 0
close(4)                                = 0
munmap(0x7f36e4a4f000, 4096)            = 0
access("/etc/selinux/config", F_OK)     = 0
access("/etc/system-fips", F_OK)        = -1 ENOENT (No such file or directory)
futex(0x7f36e3c0496c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f36e3c04978, FUTEX_WAKE_PRIVATE, 2147483647) = 0
writev(2, [{"/sbin/cbwd", 10}, {": ", 2}, {"symbol lookup error", 19}, {": ", 2}, {"/sbin/cbwd", 10}, {": ", 2}, {"undefined symbol: _ZN16QCoreAppl"..., 48}, {"", 0}, {"", 0}, {"\n", 1}], 10/sbin/cbwd: symbol lookup error: /sbin/cbwd: undefined symbol: _ZN16QCoreApplicationC1ERiPPci
) = 94
exit_group(127)                         = ?
+++ exited with 127 +++

**Comment by ganoze** [comment]
It seems that there is an issue with your Qt installation. Could you provide details on the qt package you installed ?

**Comment by ludovic-lage** [comment]
After a check of all the installed packages, effectively, I was with the wrong version of Qt for el6.
I removed the wrong packages and installe the good packages for el7 and everything is good.
Thanks for your help.

**Comment by ganoze** [comment]
No problem, thank you for your feedback.
