### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#91]
Hi,

We had a problem of duplicate entry in the database with the key 'entry_time'.
We understand that protection.
Our problem was that the database was out of date, everything was in retention files.

Would it be possible to avoid blocking all treatments when this type of problem?

Our only solution was to remove this key from the database and put it again.

**Comment by ganoze** [comment]
Could you tell me on which event/table this issue occured ?

**Comment by jben94** [comment]
Log exemple: 

[1491808344] error:   SQL: could not execute prepared statement: Duplicate entry '1491573311-5999-63047' for key 'entry_time' QMYSQL3: Unable to execute statement

We do not have more precision in the logs because we had not set the debug mode.

BDD : centreon_storage
Table : comments
Key : entry_time 

![image](https://cloud.githubusercontent.com/assets/16583698/24872959/821d4734-1e1f-11e7-9a86-e6d675d7525f.png)

**Comment by ganoze** [comment]
This should not happen with latest release of Centreon Broker, as tables with *entry_time, host_id, service_id* UNIQUE key now attempt to update first. Could you check if this fixes your problem ?

**Comment by Tomszy** [comment]
We are getting similar error message. Is this a bug?
![image](https://user-images.githubusercontent.com/25457811/29925593-1273da94-8e61-11e7-862f-d587b76ddc1a.png)

Can you fix this issue?

**Comment by jben94** [comment]
Hi,

You use what version of Centreon-Broker?
The latest version is 3.0.8.

@ganoze : I have not tested yet, I do as soon as possible.

Regards

**Comment by Tomszy** [comment]
Hi,

We are using 3.0.8.

Regards

**Comment by jben94** [comment]
Ok, are these errors blocking? 
Do you have retention files? 
Is the database information up-to-date?

Because in older versions the process looped on this error. 
And everything else was suspended

**Comment by Tomszy** [comment]
yes. It cause some problems.

We need to reload the cbd after these errors, but after the reload many service come back to pending status again and again... and some poller always stuck after this operation and we need to restart centengines after it.

So it would be great if you can fix this bug.

**Comment by jben94** [comment]
Do you know the root cause of this error?
Is this linked to the change of "Poller"?

For my part, I removed the constraints on three tables to avoid these problems while waiting for improvements. (downtimes - comments - acknowledgements => Key is "entry_time")

**Comment by Tomszy** [comment]
No I don't have any idea. I don't know too much about DB part. I hope centreon guys will fix this issue soon.

**Comment by Tomszy** [comment]
So if we remove the constraints will fix the issue?

**Comment by jben94** [comment]
The message is different because I had this error on another version of Centreon-Broker. 
But I think they are identical.

The only problem that may have after removing these constraints.
Have duplicate posting for comments or downtimes or acknowledge.

We chose to have a risk on the posting of information, but not on supervision. 
Because duplicates can be simply deleted in the database, while a shutdown of the supervision is more problematic.

**Comment by jben94** [comment]
it would be necessary to know which table causes your error, for it is true that the key is not the same, I did not look very well, sorry.

**Comment by jben94** [comment]
The key belongs to the "centeron_storage.services_servicegroups" table.

If you tap this command : 

```
SELECT    COUNT(service_service_id), centreon.servicegroup_relation.*
FROM     centreon.servicegroup_relation
GROUP BY servicegroup_sg_id, service_service_id, host_host_id
HAVING   COUNT(service_service_id) > 1;
```

you have what as output?

I noticed that I also had duplicates in the "centeron.servicegroup_relation" table.
But that was not in the "centeron_storage.services_servicegroups" table.

**Comment by zskarman** [comment]
![image](https://user-images.githubusercontent.com/24320218/30030096-0b171b84-918c-11e7-93ac-752c1f89a6d4.png)

**Comment by jben94** [comment]
As you can see you have duplicates of entry. They must be removed.

 ```
DELETE FROM centreon.servicegroup_relation WHERE host_host_id=51049 AND service_service_id=148893 AND servicegroup_sg_id=1 AND sgr_id<>1046393;
```

To avoid having other you can put unique key.

```
ALTER TABLE `centreon`.`servicegroup_relation` 
ADD UNIQUE INDEX `host_id_unique` (`host_host_id` ASC, `service_service_id` ASC, `servicegroup_sg_id` ASC),
ADD UNIQUE INDEX `hg_id_unique` (`hostgroup_hg_id` ASC, `service_service_id` ASC, `servicegroup_sg_id` ASC);
```

After removing these entries and after restarting the pollers. It might be useful to empty the "centreon_storage.services_servicegroups" table before restarting.
Do you still have the problems?

**Comment by zskarman** [comment]
Hi,

implemented the SQL scripts and let's see the result.
Also thank you for you help.

Rgs, Zsolt

**Comment by Tomszy** [comment]
It looks OK in the last 3-4 hours.

**Comment by jben94** [comment]
Hi,

I'm not completely sure that these changes are true cause of the problem because I do not see the host_id and the service_id corresponding to the log and output of the SQL query.

But it could avoid duplicates in the table "centeron.servicegroup_relation"

Must see.

**Comment by Tomszy** [comment]
We got duplicate entry again...
![image](https://user-images.githubusercontent.com/25457811/30112782-c8b0d0cc-9312-11e7-884c-362dc24fd718.png)

**Comment by jben94** [comment]
Did this host or this service change to poller?

**Comment by jben94** [comment]
Hi @ganoze,

This morning we still had errors with the key "entry_time".
This caused a block on the update of the database.

> [1505200504] error:   SQL: could not store comment (poller: 5, host: 3792, service: 40382, entry time: 1502366989, internal ID: 9630): could not execute prepared statement: Duplicate entry '3792-40382-1502366989' for key 'entry_time' QMYSQL3: Unable to execute statement

Regards

**Comment by ganoze** [comment]
Hi @jben94 . It seems that your *comments* table does not have the correct UNIQUE constraint. It should read as follow.

`
UNIQUE KEY `entry_time` (`entry_time`,`host_id`,`service_id`, `instance_id`, `internal_id`)
`

It seems like the correct UNIQUE is set with recent fresh installation of Centreon Web, whereas updated versions were forgotten. I've just filled PR https://github.com/centreon/centreon/pull/5665 to get it fixed.

@Tomszy your error is harmless. With latest Centreon Broker version it should only print error logs without any other side effect. Still, if this behavior bothers you, feel free to open another issue :-)

**Comment by jben94** [comment]
Hi @ganoze,

Ah ok, I would make the changes tomorrow.
Thank you!

**Comment by Tomszy** [comment]
Hi,

This is not harmless because when we get this issue the broker is stucking sometimes and we need to reload it. But after the reload many services come back to pending status which is not good.

Can you fix our issue as well?

Regards,

Tomszy

**Comment by zskarman** [comment]
Hi @ganoze,

Could you please have a look at for our issues as well because each of the 10 mins one of the poller has not visible on the UI and we get this error
![image](https://user-images.githubusercontent.com/24320218/30473178-cccedcbe-99ff-11e7-9e33-4699cc83b429.png)

Regards, Zsolt

**Comment by Tomszy** [comment]
And we have updated as well the broker to 3.0.9 on the broker server.
But on the pollers  we did not updated the broker packages. They are on 3.0.7. Can it cause any problem?

**Comment by zskarman** [comment]
Hi,

Just an quick comment:

on the broker
![image](https://user-images.githubusercontent.com/24320218/30535064-2437a7f2-9c61-11e7-8050-6938a78e2612.png)

and on the mysql
![image](https://user-images.githubusercontent.com/24320218/30535079-3787c15c-9c61-11e7-93e1-dc83676c23ca.png)


So it looks the issue with the broker side.
Regards, Zsolt

**Comment by zskarman** [comment]
Hi @ganoze,

Could you please have a look at for this topic: https://github.com/centreon/centreon/issues/5622
it looks connected to the broker.

Thank you!
