### ISSUE TITLE
Centreon Broker 3.0.5 - Issue

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon-broker#93]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:2.8.5 
**Centreon Engine version**:1.7.1 
**Centreon Broker version**:3.0.5 
**OS**: Oracle Linux 7
**Additional environment detail**s :Virtual
**Steps to reproduce the issue:**
1. We updated centreon to 2.8.5
2. We are getting the following errors in /var/log/centreon-broker/central-broker-master.log
3. " error: multiplexing: attempt to acknowledge more events than available central-broker-master-perfdata event queue: 84 requested, 83 acknowledged"

 
**Describe the results you received:**
We are getting many errors like this:
" error: multiplexing: attempt to acknowledge more events than available central-broker-master-perfdata event queue: 84 requested, 83 acknowledged"

**Describe the results you expected:**
We expect no errors.

![broker](https://cloud.githubusercontent.com/assets/25457811/24542829/7177b722-15fd-11e7-8ac2-938cf61e9798.PNG)

Any idea how to solve this?

Regards,

Tamas

**Comment by hocinetwork** [comment]
I confirm this behavior.

**Comment by Sims24** [comment]
Hi, 

Issue is known and under active troubleshooting. We'll provide some informations asap. 

Thanks

**Comment by hecko** [comment]
We are also experiencing this issue! 

[1493972791] [0xf068d0] error:   multiplexing: attempt to acknowledge more events than available in central-broker-perfdata-master event queue: 3865 requested, 3864 acknowledged
[1493972797] [0xf068d0] error:   multiplexing: attempt to acknowledge more events than available in central-broker-perfdata-master event queue: 3846 requested, 3845 acknowledged
[1493972803] [0xf068d0] error:   multiplexing: attempt to acknowledge more events than available in central-broker-perfdata-master event queue: 4308 requested, 4305 acknowledged


Any updates on the case? Using 3.0.5 from RPMs.

**Comment by itsul** [comment]
Same issue [https://github.com/centreon/centreon/issues/5119](url)

**Comment by ganoze** [comment]
This was fixed in the 3.0.6 release of Centreon Broker. Perfdata parsing errors triggered the acknowledgement of the current event, which is incorrect.
