### ISSUE TITLE
Increase the number of INSERT SQL

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#95]
Hi,

Since we upgraded our Centreon platform (Web 2.7.6> 2.8.5, Centengine 1.7.0> 1.7.1, Broker 2.11.5> 3.0.5), we have a lot of SQL query 'INSERT' increased.

I was wondering if the next change "https://github.com/centreon/centreon-broker/commit/23815387e2f5840c501e466856b1cfce2a56d0a1#diff-7cae814a52e36dbae30e97dbcd96e4b8" would not cause it?
If I understand correctly, you no longer work in Transactional.

The update was at April 04:

![image](https://cloud.githubusercontent.com/assets/16583698/25125490/52c1a884-242f-11e7-96e8-f752b460314d.png)

**Comment by jben94** [comment]
du avril 08 au avril 10, nous avons eu un problème sur les graphs. C'est pour celà que nous avons une chute et un pic.

**Comment by jben94** [comment]
From April 08 to April 10, we had a problem on the graphs. That's why we have a fall and a peak.

**Comment by ganoze** [comment]
Indeed the number of INSERT queries increased in the 3.0 release. Previously, performance data were inserted in bulk queries (INSERT with multiple VALUES). Now we work with prepared statements, one performance data at a time, but still in transactional.

This should explain the INSERT increase that you had.

**Comment by jben94** [comment]
Ok, in fact this increase of Insert, we also increased binlog + 40GB.

**Comment by ganoze** [comment]
I'm closing this ticket in favor of #109 where I reverted back to bulk INSERT in data_bin. This should decrease your number of INSERT statements.
