### ISSUE TITLE
InfluxDB - Escape

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-broker#97]
Hi,

I encounter problems on sends to the base influxdb.
The name of the metrics are not escape.

Example : 

"centreon.metrics.localhost.bytesSent_JMX.Bytes Sent"

> Content-Type: application/json
> Request-Id: 2467be24-2b38-11e7-897f-000000000000
> X-Influxdb-Version: 1.1.1
> Date: Thu, 27 Apr 2017 10:56:18 GMT
> Content-Length: 175
> 
> {"error":"partial write:\nunable to parse 'centreon.metrics.localhost.bytesSent_JMX.Bytes Sent,metric_id=1595751 value=\"1.93092e+07\" 1493290073': invalid field format"}
> '

**Comment by jben94** [comment]
The other metrics works well and when I do the test in CLI I notice that it does not like space in the metric name.
The timestamp is set automatically by Centreon.

**Comment by george-vieira** [comment]
Oh Sorry, yes, I missed the space between Bytes and Sent. that does breaks the format as the metric vs value is space separated. this isn't really a bug with centreon but a expected format of influxdb/graphite and so on. You'll just need to underscore it or something.

**Comment by jben94** [comment]
Yes you are right, but Centreon allows spaces in the names of metrics and not influxDB. In the sending connector to the influxDB database, you would need a name corrector.

**Comment by ganoze** [comment]
After having a look at it, it seems that escaping is not properly applied when building Line Protocol queries. Indeed InfluxDB escaping is quite tricky and depends on the query parts (measurement, tags or fields) as per https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_tutorial/

The current implementation does not easily allow different escaping schemes so I'll rework the code to make it work properly.

**Comment by ganoze** [comment]
I have just merged some commits to implement the different escaping schemes. So now everything should work fine, even with whitespaces or special chars.

**Comment by jben94** [comment]
Ok, thanks you
